In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
not_squeezed = tf.constant(tf.random.normal(shape=[33]), shape=(1,1,1,1,33))
not_squeezed

<tf.Tensor: shape=(1, 1, 1, 1, 33), dtype=float32, numpy=
array([[[[[ 0.29960027,  0.43005905,  0.10210532, -0.39108223,
            0.14770809, -0.0128903 , -0.7366861 , -1.3836375 ,
           -0.9742985 , -0.41535553, -1.2561595 ,  0.25588834,
           -0.9690718 , -0.5360929 , -0.18513162, -0.07544754,
            0.7073354 , -0.56442744,  0.05409355, -0.25717145,
            0.26408005,  0.8120168 ,  0.15951939, -0.10761449,
           -0.6612721 ,  0.28474224,  0.06519309,  0.9596827 ,
            0.01993348,  2.2543216 , -0.49828184,  2.0438335 ,
           -0.6971201 ]]]]], dtype=float32)>

In [6]:
tf.squeeze(not_squeezed)

<tf.Tensor: shape=(33,), dtype=float32, numpy=
array([ 0.29960027,  0.43005905,  0.10210532, -0.39108223,  0.14770809,
       -0.0128903 , -0.7366861 , -1.3836375 , -0.9742985 , -0.41535553,
       -1.2561595 ,  0.25588834, -0.9690718 , -0.5360929 , -0.18513162,
       -0.07544754,  0.7073354 , -0.56442744,  0.05409355, -0.25717145,
        0.26408005,  0.8120168 ,  0.15951939, -0.10761449, -0.6612721 ,
        0.28474224,  0.06519309,  0.9596827 ,  0.01993348,  2.2543216 ,
       -0.49828184,  2.0438335 , -0.6971201 ], dtype=float32)>

In [7]:
val = tf.constant([
                   [3,5],[6,7],[8,3],[3,5]
])
val

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [8, 3],
       [3, 5]], dtype=int32)>

In [8]:
tf.one_hot(val, depth=4)

<tf.Tensor: shape=(4, 2, 4), dtype=float32, numpy=
array([[[0., 0., 0., 1.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 1.]],

       [[0., 0., 0., 1.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [9]:
tf.one_hot(val, depth=4, on_value='I am On Value', off_value='I am off value')


<tf.Tensor: shape=(4, 2, 4), dtype=string, numpy=
array([[[b'I am off value', b'I am off value', b'I am off value',
         b'I am On Value'],
        [b'I am off value', b'I am off value', b'I am off value',
         b'I am off value']],

       [[b'I am off value', b'I am off value', b'I am off value',
         b'I am off value'],
        [b'I am off value', b'I am off value', b'I am off value',
         b'I am off value']],

       [[b'I am off value', b'I am off value', b'I am off value',
         b'I am off value'],
        [b'I am off value', b'I am off value', b'I am off value',
         b'I am On Value']],

       [[b'I am off value', b'I am off value', b'I am off value',
         b'I am On Value'],
        [b'I am off value', b'I am off value', b'I am off value',
         b'I am off value']]], dtype=object)>

In [11]:
tf.range(3,4)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [12]:
tf.math.square(val)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 9, 25],
       [36, 49],
       [64,  9],
       [ 9, 25]], dtype=int32)>

In [14]:
tf.math.sqrt(tf.cast(val, dtype=tf.float32))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1.7320508, 2.236068 ],
       [2.4494896, 2.6457512],
       [2.8284268, 1.7320508],
       [1.7320508, 2.236068 ]], dtype=float32)>

In [15]:
tf.math.log(tf.cast(val, dtype=tf.float32))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1.0986123, 1.609438 ],
       [1.7917595, 1.9459102],
       [2.0794415, 1.0986123],
       [1.0986123, 1.609438 ]], dtype=float32)>

In [17]:
numpy_A = tf.constant(np.array([[2,3],[5,3]]))
tensor_A = tf.constant([[2,3],[5,3]])


In [18]:
numpy_A, tensor_A

(<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[2, 3],
        [5, 3]])>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 3],
        [5, 3]], dtype=int32)>)

In [19]:
numpy_A.dtype, tensor_A.dtype

(tf.int64, tf.int32)

**Model No 1**

In [20]:
X = tf.constant([2,4,6,8,10,12])
y= tf.constant([3,6,9,12,15,18])


In [21]:
X,y

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10, 12], dtype=int32)>,
 <tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15, 18], dtype=int32)>)

In [23]:
# set Random Value
tf.random.set_seed(42)

# Create A model

model = tf.keras.Sequential([
                             tf.keras.layers.Dense(1)
])

# Compiling a model

model.compile(
    loss = tf.keras.losses.mae,
    optimizer = tf.keras.optimizers.SGD(),
    metrics=['mae']
)

#  fit a model

model.fit(tf.expand_dims(X,axis=1), y, epochs=5)


# Evaluate a model

model.evaluate(X, y)


Epoch 1/5
1/1 [==============================] - 1s 572ms/step - loss: 6.5096 - mae: 6.5096
Epoch 2/5
1/1 [==============================] - 0s 9ms/step - loss: 6.0096 - mae: 6.0096
Epoch 3/5
1/1 [==============================] - 0s 8ms/step - loss: 5.5096 - mae: 5.5096
Epoch 4/5
1/1 [==============================] - 0s 6ms/step - loss: 5.0096 - mae: 5.0096
Epoch 5/5
1/1 [==============================] - 0s 107ms/step - loss: 4.0096 - mae: 4.0096


[4.009581089019775, 4.009581089019775]

In [24]:
X , y

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10, 12], dtype=int32)>,
 <tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15, 18], dtype=int32)>)

In [26]:
model.predict([14])

array([[12.930839]], dtype=float32)

**Model No 2**

In [27]:
# Set Random Value
tf.random.set_seed(42)

# Create A model
model = tf.keras.Sequential([
                           tf.keras.layers.Dense(1)  
])

# compiling a model

model.compile(
    loss= tf.keras.losses.mae,
    optimizer = tf.keras.optimizers.SGD(),
    metrics=['mae']
)

# Fit a model

model.fit(tf.expand_dims(X, axis=1), y, epochs=100)

# Evaluate a model

model.evaluate(X,y)

Epoch 1/100
1/1 [==============================] - 0s 234ms/step - loss: 6.5096 - mae: 6.5096
Epoch 2/100
1/1 [==============================] - 0s 5ms/step - loss: 6.0096 - mae: 6.0096
Epoch 3/100
1/1 [==============================] - 0s 3ms/step - loss: 5.5096 - mae: 5.5096
Epoch 4/100
1/1 [==============================] - 0s 5ms/step - loss: 5.0096 - mae: 5.0096
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 4.5096 - mae: 4.5096
Epoch 6/100
1/1 [==============================] - 0s 5ms/step - loss: 4.0096 - mae: 4.0096
Epoch 7/100
1/1 [==============================] - 0s 7ms/step - loss: 3.5096 - mae: 3.5096
Epoch 8/100
1/1 [==============================] - 0s 5ms/step - loss: 3.0096 - mae: 3.0096
Epoch 9/100
1/1 [==============================] - 0s 4ms/step - loss: 2.5096 - mae: 2.5096
Epoch 10/100
1/1 [==============================] - 0s 4ms/step - loss: 2.0096 - mae: 2.0096
Epoch 11/100
1/1 [==============================] - 0s 4ms/step - loss: 1.509

[0.15042150020599365, 0.15042150020599365]

In [28]:
X, y

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10, 12], dtype=int32)>,
 <tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15, 18], dtype=int32)>)

In [29]:
model.predict([14])

array([[21.174177]], dtype=float32)

**Model No 3**

In [30]:
tf.random.set_seed(42)


model =  tf.keras.Sequential([
                              tf.keras.layers.Dense(100, activation='relu'),
                              tf.keras.layers.Dense(1)
])

model.compile(
    loss = tf.keras.losses.mae,
    optimizer = tf.keras.optimizers.SGD(),
    metrics=['mae']
)

model.fit(tf.expand_dims(X, axis=1), y, epochs=100)

model.evaluate(X,y)

Epoch 1/100
1/1 [==============================] - 0s 308ms/step - loss: 9.0186 - mae: 9.0186
Epoch 2/100
1/1 [==============================] - 0s 4ms/step - loss: 8.0342 - mae: 8.0342
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 7.0267 - mae: 7.0267
Epoch 4/100
1/1 [==============================] - 0s 5ms/step - loss: 5.9718 - mae: 5.9718
Epoch 5/100
1/1 [==============================] - 0s 3ms/step - loss: 4.8375 - mae: 4.8375
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 3.6021 - mae: 3.6021
Epoch 7/100
1/1 [==============================] - 0s 3ms/step - loss: 2.2621 - mae: 2.2621
Epoch 8/100
1/1 [==============================] - 0s 3ms/step - loss: 0.7896 - mae: 0.7896
Epoch 9/100
1/1 [==============================] - 0s 4ms/step - loss: 0.8609 - mae: 0.8609
Epoch 10/100
1/1 [==============================] - 0s 3ms/step - loss: 0.8857 - mae: 0.8857
Epoch 11/100
1/1 [==============================] - 0s 3ms/step - loss: 0.748

[0.6295583248138428, 0.6295583248138428]

In [31]:
X, y

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10, 12], dtype=int32)>,
 <tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15, 18], dtype=int32)>)

In [32]:
model.predict([14])

array([[19.620886]], dtype=float32)

**Model No 4**

In [34]:
tf.random.set_seed(42)

model= tf.keras.Sequential([
                            tf.keras.layers.Dense(100,activation='relu'),
                            tf.keras.layers.Dense(1)
])

model.compile(
    loss = tf.keras.losses.mae,
    optimizer = tf.keras.optimizers.Adam(lr=0.01),
    metrics=['mae']
)


model.fit(tf.expand_dims(X, axis=1), y, epochs=100)

model.evaluate(X,y)

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/100
1/1 [==============================] - 0s 331ms/step - loss: 9.0186 - mae: 9.0186
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 8.0628 - mae: 8.0628
Epoch 3/100
1/1 [==============================] - 0s 3ms/step - loss: 7.0930 - mae: 7.0930
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 6.1058 - mae: 6.1058
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 5.0865 - mae: 5.0865
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 4.0344 - mae: 4.0344
Epoch 7/100
1/1 [==============================] - 0s 4ms/step - loss: 2.9514 - mae: 2.9514
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 1.8268 - mae: 1.8268
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7600 - mae: 0.7600
Epoch 10/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5539 - mae: 0.5539
Epoch 11/100
1/1 [==============================] - 0s 5ms/step - loss: 1.335

[0.005490779876708984, 0.005490779876708984]

In [35]:
X,y

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10, 12], dtype=int32)>,
 <tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15, 18], dtype=int32)>)

In [36]:
model.predict([14])

array([[20.989462]], dtype=float32)