In [14]:
import tensorflow as tf
import numpy as np
import math as mt

# Aggregate

In [2]:
agg = tf.constant([-1,-4,-5,-6])
agg

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -4, -5, -6], dtype=int32)>

In [3]:
tf.abs(agg)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 4, 5, 6], dtype=int32)>

In [4]:
E = tf.constant(np.random.randint(0,100,size=50))

In [5]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([82, 89, 81, 95, 15, 97, 58, 13, 41, 87, 76, 50, 76, 19,  5,  6, 22,
       76, 82, 22, 10, 61,  6, 97,  3, 52, 20, 83, 93, 42, 92, 52, 16, 44,
       42, 26,  6, 73, 18, 50, 95,  2, 94, 31,  6, 82, 22, 86, 33, 98])>

In [6]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [7]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [8]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [9]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2527>

In [21]:
variance = tf.reduce_max(E)-tf.reduce_min(E)
variance = variance/2527-1

In [22]:
variance

<tf.Tensor: shape=(), dtype=float64, numpy=-0.962010288880095>

In [18]:
variance = tf.math.sqrt(variance)


In [19]:
variance

<tf.Tensor: shape=(), dtype=float64, numpy=nan>

In [20]:
variance

<tf.Tensor: shape=(), dtype=float64, numpy=nan>

In [23]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [24]:
F= tf.constant(np.random.randint(0,50,size=25))
F

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([ 5, 33, 29, 43, 18, 21,  7,  0, 48, 28, 13, 33, 20, 24, 28,  0, 45,
        7, 15, 26, 13, 31,  4,  2, 31])>

In [25]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [26]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [27]:
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [28]:
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=524>