###Basic Opearation

In [2]:
import tensorflow as tf
import numpy as np

tensor = tf.constant([
                      [1,2],[4,6],[7,9]
])

tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 6],
       [7, 9]], dtype=int32)>

In [3]:
tensor+10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 12],
       [14, 16],
       [17, 19]], dtype=int32)>

In [4]:
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 6],
       [7, 9]], dtype=int32)>

In [5]:
tensor-10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[-9, -8],
       [-6, -4],
       [-3, -1]], dtype=int32)>

In [6]:
tensor*10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [40, 60],
       [70, 90]], dtype=int32)>

In [7]:
tensor/10

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.1, 0.2],
       [0.4, 0.6],
       [0.7, 0.9]])>

In [8]:
tensor**4

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[   1,   16],
       [ 256, 1296],
       [2401, 6561]], dtype=int32)>

In [9]:
tf.math.add(tensor, 12)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[13, 14],
       [16, 18],
       [19, 21]], dtype=int32)>

In [12]:
tf.math.subtract(tensor,10)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[-9, -8],
       [-6, -4],
       [-3, -1]], dtype=int32)>

In [14]:
tf.math.multiply(tensor,10)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [40, 60],
       [70, 90]], dtype=int32)>

In [15]:
tf.math.divide(tensor,19)

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.05263158, 0.10526316],
       [0.21052632, 0.31578947],
       [0.36842105, 0.47368421]])>