#Basic_Practice_Tensor_Flow

In [1]:
import tensorflow as tf
import numpy as np

**Constant**

In [2]:
scalar = tf.constant(1,3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [3]:
vector = tf.constant([1,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [4]:
matrix = tf.constant([
                      [1,4],[5,2]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [5, 2]], dtype=int32)>

In [6]:
tensors = tf.constant([
                       [1,4],[5,3],[5,2],[5,6]
], dtype=tf.float32)
tensors

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 4.],
       [5., 3.],
       [5., 2.],
       [5., 6.]], dtype=float32)>

**Variable**

In [8]:
variable = tf.Variable([1,4])

In [9]:
variable[0].assign(4)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 4], dtype=int32)>

In [10]:
variable[1].assign(5)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [11]:
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

**Random Generator**

In [13]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(4,5))
random_1

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
       [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
       [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ],
       [ 1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085]],
      dtype=float32)>

In [14]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(4,5))
random_2

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ],
       [0.52027524, 0.8736881 , 0.46921718, 0.63932586, 0.6467117 ],
       [0.96246755, 0.41009164, 0.86540747, 0.8862978 , 0.27795732],
       [0.8857763 , 0.2179842 , 0.29115117, 0.03953862, 0.8136791 ]],
      dtype=float32)>

In [15]:
random_1==random_2

<tf.Tensor: shape=(4, 5), dtype=bool, numpy=
array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])>

**Shuffle**

In [19]:
shuffling = tf.constant([
                         [3,4],[5,3],[6,3]
])
not_shuffled = tf.random.shuffle(shuffling)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 3],
       [3, 4],
       [6, 3]], dtype=int32)>

In [27]:
not_shuffled = tf.random.shuffle(shuffling, seed=42)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [6, 3],
       [5, 3]], dtype=int32)>

In [32]:
tf.random.set_seed(42)
not_shuffled = tf.random.shuffle(shuffling, seed=42)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 3],
       [6, 3]], dtype=int32)>

**Concept Of Numpy**

In [34]:
numpy_A = np.arange(1,30, dtype=np.float32)
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29.], dtype=float32)

In [36]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(29,), dtype=float32, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29.], dtype=float32)>

In [37]:
numpy_A == tensor_A

<tf.Tensor: shape=(29,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])>

In [38]:
numpy_A.dtype, tensor_A.dtype

(dtype('float32'), tf.float32)

**Getting Information**

In [39]:
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29.], dtype=float32)

In [41]:
print(numpy_A.size)
print(numpy_A.ndim)
print(numpy_A.itemsize)
print(numpy_A.shape)
print(numpy_A.shape[0])
print(numpy_A.shape[-1])
print(numpy_A.dtype)
print(numpy_A.nbytes)
print(tf.size(numpy_A))
print(tf.size(numpy_A).numpy())

29
1
4
(29,)
29
29
float32
116
tf.Tensor(29, shape=(), dtype=int32)
29


In [43]:
numpy_A.shape

(29,)

In [44]:
numpy_A.ravel()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29.], dtype=float32)

**Indexing**

In [42]:
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29.], dtype=float32)

In [45]:
numpy_A[1]

2.0

In [46]:
numpy_A[1:4]

array([2., 3., 4.], dtype=float32)

In [47]:
numpy_A[1:20:2]

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.], dtype=float32)

In [49]:
numpy_B = numpy_A[..., tf.newaxis]
numpy_B

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.],
       [12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.],
       [24.],
       [25.],
       [26.],
       [27.],
       [28.],
       [29.]], dtype=float32)

In [50]:
numpy_B.shape

(29, 1)

In [52]:
numpy_C = np.expand_dims(numpy_A, axis=0)
numpy_C

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29.]], dtype=float32)

In [54]:
numpy_C.shape

(1, 29)

**Basic Operations**

In [55]:
numpy_A + 10

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
       24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36.,
       37., 38., 39.], dtype=float32)

In [56]:
numpy_A - 10

array([-9., -8., -7., -6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.,
       17., 18., 19.], dtype=float32)

In [57]:
numpy_A * 10

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.,
       120., 130., 140., 150., 160., 170., 180., 190., 200., 210., 220.,
       230., 240., 250., 260., 270., 280., 290.], dtype=float32)

In [58]:
numpy_A / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9], dtype=float32)

In [59]:
numpy_A ** 10

array([1.0000000e+00, 1.0240000e+03, 5.9049000e+04, 1.0485760e+06,
       9.7656250e+06, 6.0466176e+07, 2.8247526e+08, 1.0737418e+09,
       3.4867845e+09, 1.0000000e+10, 2.5937424e+10, 6.1917364e+10,
       1.3785850e+11, 2.8925467e+11, 5.7665041e+11, 1.0995116e+12,
       2.0159939e+12, 3.5704673e+12, 6.1310663e+12, 1.0240000e+13,
       1.6679881e+13, 2.6559923e+13, 4.1426511e+13, 6.3403381e+13,
       9.5367434e+13, 1.4116710e+14, 2.0589114e+14, 2.9619678e+14,
       4.2070725e+14], dtype=float32)

In [60]:
tf.math.add(10, numpy_A)

<tf.Tensor: shape=(29,), dtype=int32, numpy=
array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39], dtype=int32)>

In [61]:
tf.math.subtract(10, numpy_A)

<tf.Tensor: shape=(29,), dtype=int32, numpy=
array([  9,   8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,
        -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13, -14, -15, -16,
       -17, -18, -19], dtype=int32)>

In [62]:
tf.math.multiply(10, numpy_A)

<tf.Tensor: shape=(29,), dtype=int32, numpy=
array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260,
       270, 280, 290], dtype=int32)>

In [63]:
tf.math.divide(10, numpy_A)

<tf.Tensor: shape=(29,), dtype=float64, numpy=
array([10.        ,  5.        ,  3.33333333,  2.5       ,  2.        ,
        1.66666667,  1.42857143,  1.25      ,  1.11111111,  1.        ,
        0.90909091,  0.83333333,  0.76923077,  0.71428571,  0.66666667,
        0.625     ,  0.58823529,  0.55555556,  0.52631579,  0.5       ,
        0.47619048,  0.45454545,  0.43478261,  0.41666667,  0.4       ,
        0.38461538,  0.37037037,  0.35714286,  0.34482759])>

**Matrix Multiplication**

In [64]:
matrix1 = tf.constant([
                       [2,4],[6,4],[6,3]
])


In [65]:
matrix2 = tf.constant([
                       [3,4],[7,4],[8,2]
])

In [66]:
tf.matmul(matrix1, matrix2)

InvalidArgumentError: ignored

In [67]:
tf.matmul(tf.transpose(matrix1), matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[96, 44],
       [64, 38]], dtype=int32)>

In [68]:
tf.matmul(matrix1, tf.transpose(matrix2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[22, 30, 24],
       [34, 58, 56],
       [30, 54, 54]], dtype=int32)>

In [69]:
matrix1.shape, matrix2.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [73]:
tf.reshape(matrix1, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 4, 6],
       [4, 6, 3]], dtype=int32)>

In [74]:
tf.matmul(tf.reshape(matrix1, shape=(2,3)), matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[82, 36],
       [78, 46]], dtype=int32)>

In [75]:
tf.matmul(matrix1, tf.reshape(matrix1, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[20, 32, 24],
       [28, 48, 48],
       [24, 42, 45]], dtype=int32)>

**Change Data Type**

In [76]:
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29.], dtype=float32)

In [79]:
tf.cast(numpy_A, dtype=tf.float16)

<tf.Tensor: shape=(29,), dtype=float16, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29.], dtype=float16)>

In [80]:
tf.cast(numpy_A, dtype=tf.int32)

<tf.Tensor: shape=(29,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int32)>

**Aggregate**

In [81]:
numpy_B = tf.constant([
                       [-1,-4],[-7,-5],[-7,-3]
])
numpy_B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[-1, -4],
       [-7, -5],
       [-7, -3]], dtype=int32)>

In [83]:
tf.abs(numpy_B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [7, 5],
       [7, 3]], dtype=int32)>

In [85]:
print(tf.reduce_min(numpy_B))
print(tf.reduce_max(numpy_B))
print(tf.reduce_mean(numpy_B))
print(tf.reduce_sum(numpy_B))

tf.Tensor(-7, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(-4, shape=(), dtype=int32)
tf.Tensor(-27, shape=(), dtype=int32)


**Variance and Standard Deviation**

In [87]:
tf.math.reduce_variance(tf.cast(numpy_B, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=4.5833335>

In [88]:
tf.math.reduce_std(tf.cast(numpy_B, dtype= tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.1408722>

**Argmax and Argmin**

In [89]:
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29.], dtype=float32)

In [90]:
np.argmax(numpy_A)

28

In [91]:
np.argmin(numpy_A)

0

In [92]:
np.argsort(numpy_A)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])