In [1]:
import tensorflow as tf
import numpy as np

#Change Datatype


In [2]:
matrix1= tf.constant([1,4])
matrix1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [3]:
matrix2 = tf.constant([1.1,4.8])
matrix2

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.1, 4.8], dtype=float32)>

In [5]:
matrix3= tf.cast(matrix1, dtype=tf.int16)

In [6]:
matrix3

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 4], dtype=int16)>

In [7]:
matrix3= tf.cast(matrix1, dtype=tf.float16)
matrix3

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 4.], dtype=float16)>

In [8]:
matrix3= tf.cast(matrix1,dtype=tf.float32)
matrix3

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 4.], dtype=float32)>

In [9]:
matrix3

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 4.], dtype=float32)>

In [10]:
matrix3.dtype

tf.float32