In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.6.0


In [5]:
scalar = tf.constant(6)

In [6]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [7]:
scalar.ndim

0

In [11]:
scalar2 = tf.constant([0,3])
scalar2

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 3], dtype=int32)>

In [12]:
scalar2.ndim

1

In [15]:
vector = tf.constant([[3,4], [5,6]])
vector

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [17]:
vector.ndim

2

In [18]:
another_matrix = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
another_matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [19]:
another_matrix.ndim

2

In [29]:
matrix_version = tf.constant([
          [[1,2,3], [4,5,6], [7,8,9]]  ,
          [[11,12,13], [14,15,16], [17,18,19]],
          [[20,21,22],[23,24,25],[26,27,28]],         
],dtype=tf.float32)

matrix_version

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]],

       [[20., 21., 22.],
        [23., 24., 25.],
        [26., 27., 28.]]], dtype=float32)>

In [23]:
matrix_version.ndim

3