##Getting Information From Tensor##


In [2]:
import tensorflow as tf
import numpy as np

rank_4_tensor = tf.zeros([1,2,3,4])

rank_4_tensor

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [3]:
rank_4_tensor[0]

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [4]:
rank_4_tensor.shape

TensorShape([1, 2, 3, 4])

In [5]:
rank_4_tensor.ndim

4

In [6]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [16]:
print(rank_4_tensor.dtype)
print(rank_4_tensor.ndim)
print(rank_4_tensor.shape)
print(rank_4_tensor.shape[0])
print(rank_4_tensor.shape[-1])
print(tf.size(rank_4_tensor))
print(tf.size(rank_4_tensor).numpy())

<dtype: 'float32'>
4
(1, 2, 3, 4)
1
4
tf.Tensor(24, shape=(), dtype=int32)
24


In [17]:
ranking = tf.ones(shape=(2,3,4))

In [18]:
ranking

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [19]:
ranking.dtype
ranking.ndim
ranking.shape
ranking.shape[0]
ranking.shape[-1]
tf.size(ranking)
tf.size(ranking).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=24>>

In [20]:
print(ranking.dtype)
print(ranking.ndim)
print(ranking.shape)
print(ranking.shape[0])
print(ranking.shape[-1])
print(tf.size(ranking))
print(tf.size(ranking).numpy())

<dtype: 'float32'>
3
(2, 3, 4)
2
4
tf.Tensor(24, shape=(), dtype=int32)
24
