# ***Improving The model*** 

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot  as plt

In [2]:
X = tf.constant([3,6,9,12,15,18])
y =tf.constant([4,8,12,16,20,24])
 
X,y 

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15, 18], dtype=int32)>,
 <tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 4,  8, 12, 16, 20, 24], dtype=int32)>)

**Model No 1**

In [3]:
#set random values
tf.random.set_seed(42)

# create A model
model = tf.keras.Sequential([
                             tf.keras.layers.Dense(1)
])

# compiling a model

model.compile(
    loss= tf.keras.losses.mae,
    optimizer = tf.keras.optimizers.SGD(),
    metrics = ['mae']    
)

# Fit a model

model.fit(tf.expand_dims(X, axis=1), y, epochs=5)

# evaluate a model

model.evaluate(X, y)

Epoch 1/5
1/1 [==============================] - 1s 627ms/step - loss: 8.0144 - mae: 8.0144
Epoch 2/5
1/1 [==============================] - 0s 5ms/step - loss: 6.9019 - mae: 6.9019
Epoch 3/5
1/1 [==============================] - 0s 4ms/step - loss: 5.7894 - mae: 5.7894
Epoch 4/5
1/1 [==============================] - 0s 4ms/step - loss: 4.6769 - mae: 4.6769
Epoch 5/5
1/1 [==============================] - 0s 131ms/step - loss: 2.4519 - mae: 2.4519


[2.4518699645996094, 2.4518699645996094]

In [4]:
X,y

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15, 18], dtype=int32)>,
 <tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 4,  8, 12, 16, 20, 24], dtype=int32)>)

In [5]:
model.predict([21])

array([[23.046259]], dtype=float32)

**Model No 2**

In [7]:
# set Random Values 

tf.random.set_seed(42)

# create a model
model = tf.keras.Sequential([
                             tf.keras.layers.Dense(1)
])

# compiling a model 

model.compile(
    loss = tf.keras.losses.mae,
    optimizer = tf.keras.optimizers.SGD(),
    metrics=['mae']
)

# Fit a model

model.fit(tf.expand_dims(X, axis=1) ,y , epochs=100)

# evaluate the model

model.evaluate

Epoch 1/100
1/1 [==============================] - 0s 283ms/step - loss: 8.0144 - mae: 8.0144
Epoch 2/100
1/1 [==============================] - 0s 5ms/step - loss: 6.9019 - mae: 6.9019
Epoch 3/100
1/1 [==============================] - 0s 10ms/step - loss: 5.7894 - mae: 5.7894
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 4.6769 - mae: 4.6769
Epoch 5/100
1/1 [==============================] - 0s 8ms/step - loss: 3.5644 - mae: 3.5644
Epoch 6/100
1/1 [==============================] - 0s 4ms/step - loss: 2.4519 - mae: 2.4519
Epoch 7/100
1/1 [==============================] - 0s 8ms/step - loss: 1.3394 - mae: 1.3394
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 0.2269 - mae: 0.2269
Epoch 9/100
1/1 [==============================] - 0s 7ms/step - loss: 0.8856 - mae: 0.8856
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2269 - mae: 0.2269
Epoch 11/100
1/1 [==============================] - 0s 8ms/step - loss: 0.88

<bound method Model.evaluate of <keras.engine.sequential.Sequential object at 0x7f9420e9f9d0>>

In [8]:
X,y

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15, 18], dtype=int32)>,
 <tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 4,  8, 12, 16, 20, 24], dtype=int32)>)

In [9]:
model.predict([21])

array([[29.691261]], dtype=float32)

**Model No 3**

In [10]:
# set random values

tf.random.set_seed(42)

# create a model

model = tf.keras.Sequential([
                             tf.keras.layers.Dense(100, activation='relu'),
                             tf.keras.layers.Dense(1)
])

# Compile a model

model.compile(
    loss =tf.keras.losses.mae,
    optimizer = tf.keras.optimizers.SGD(),
    metrics=['mae']
)

# fit a model
model.fit(tf.expand_dims(X, axis=1) , y, epochs=100)
# evaluate a model

model.evaluate(X, y)

Epoch 1/100
1/1 [==============================] - 0s 328ms/step - loss: 11.7779 - mae: 11.7779
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 9.5888 - mae: 9.5888
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 7.3008 - mae: 7.3008
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 4.7721 - mae: 4.7721
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 1.9172 - mae: 1.9172
Epoch 6/100
1/1 [==============================] - 0s 7ms/step - loss: 1.3534 - mae: 1.3534
Epoch 7/100
1/1 [==============================] - 0s 12ms/step - loss: 2.1837 - mae: 2.1837
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 1.0148 - mae: 1.0148
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 2.4442 - mae: 2.4442
Epoch 10/100
1/1 [==============================] - 0s 8ms/step - loss: 0.6837 - mae: 0.6837
Epoch 11/100
1/1 [==============================] - 0s 6ms/step - loss: 2.

[2.2656795978546143, 2.2656795978546143]

In [11]:
X , y

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15, 18], dtype=int32)>,
 <tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 4,  8, 12, 16, 20, 24], dtype=int32)>)

In [12]:
model.predict([21])

array([[32.40925]], dtype=float32)

**Model No 4**

In [24]:
# set random values
tf.random.set_seed(42)

# create a Model

model = tf.keras.Sequential([
                             tf.keras.layers.Dense(100, activation='relu'),
                             tf.keras.layers.Dense(1)
])


# compile a model

model.compile(
    loss = tf.keras.losses.mae,
    optimizer = tf.keras.optimizers.Adam(lr=0.01),
    metrics=['mae']
)

# fit a model

model.fit(tf.expand_dims(X, axis=1), y , epochs=100 )

# Evaluate a model

model.evaluate(X, y)

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/100
1/1 [==============================] - 0s 372ms/step - loss: 11.7779 - mae: 11.7779
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 10.3819 - mae: 10.3819
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 8.9656 - mae: 8.9656
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 7.5244 - mae: 7.5244
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 6.0375 - mae: 6.0375
Epoch 6/100
1/1 [==============================] - 0s 4ms/step - loss: 4.5014 - mae: 4.5014
Epoch 7/100
1/1 [==============================] - 0s 6ms/step - loss: 2.9208 - mae: 2.9208
Epoch 8/100
1/1 [==============================] - 0s 7ms/step - loss: 1.2986 - mae: 1.2986
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 0.4119 - mae: 0.4119
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 1.4689 - mae: 1.4689
Epoch 11/100
1/1 [==============================] - 0s 7ms/step - loss: 

[0.027069369331002235, 0.027069369331002235]

In [25]:
X, y

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15, 18], dtype=int32)>,
 <tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 4,  8, 12, 16, 20, 24], dtype=int32)>)

In [26]:
model.predict([21])

array([[27.947277]], dtype=float32)