##Indexing and NewAxis In Tensors

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
some_list = [1,2,3,4,5,6,7,8,9,0]
some_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [3]:
some_list[:1]

[1]

In [7]:
some_list[:0]

[]

In [10]:
some_list[:2]

[1, 2]

In [11]:
rank_4_tensor = tf.zeros(shape=(2,3,4,6))

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 6), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]], dtype=float32)>

In [12]:
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 6), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0., 0.]]]], dtype=float32)>

In [13]:
rank_4_tensor[:1,:,:,:1]

<tf.Tensor: shape=(1, 3, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [14]:
rank_4_tensor[...]

<tf.Tensor: shape=(2, 3, 4, 6), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]], dtype=float32)>

In [15]:
rank_3_tensor = rank_4_tensor[...,tf.newaxis]

In [16]:
rank_3_tensor

<tf.Tensor: shape=(2, 3, 4, 6, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
         

In [17]:
rank_3_tensor==rank_4_tensor

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [19]:
tf.expand_dims(rank_3_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 3, 4, 6, 1), dtype=float32, numpy=
array([[[[[[0.],
           [0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.],
           [0.]]],


         [[[0.],
           [0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.],
           [0.]]],


         [[[0.],
           [0.],
           [0.],
           [0.],
           [0.],
           [0.]],



In [20]:
list_files = [2,31,4,14,1,41,4,14,14,1,5,15,1,51,31]
list_files

[2, 31, 4, 14, 1, 41, 4, 14, 14, 1, 5, 15, 1, 51, 31]

In [21]:
list_files[:2]

[2, 31]

In [24]:
list_files[:]

[2, 31, 4, 14, 1, 41, 4, 14, 14, 1, 5, 15, 1, 51, 31]

In [25]:
list_files[:3]

[2, 31, 4]

In [26]:
tensor_1_list = tf.constant([
                             [1,3],[4,5],[5,3]
])

tensor_1_list

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 5],
       [5, 3]], dtype=int32)>

In [27]:
tensor_1_list[:1,:1]

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[1]], dtype=int32)>

In [28]:
tensor_1_list[...]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 5],
       [5, 3]], dtype=int32)>

##CREATING NEW AXIS

In [29]:
tensor_2_list = tensor_1_list[...,tf.newaxis]

In [30]:
tensor_2_list

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [3]],

       [[4],
        [5]],

       [[5],
        [3]]], dtype=int32)>

In [35]:
tensor_3_list = tf.expand_dims(tensor_2_list, axis=-1)

In [36]:
tensor_3_list

<tf.Tensor: shape=(3, 2, 1, 1), dtype=int32, numpy=
array([[[[1]],

        [[3]]],


       [[[4]],

        [[5]]],


       [[[5]],

        [[3]]]], dtype=int32)>