In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor1= tf.constant([
                      [1,3,4],[2,5,8],[3,2,6]
])


In [3]:
tensor2= tf.constant([
                      [3,5,6],[6,2,7],[7,3,7]
])


In [5]:
tensor2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [6, 2, 7],
       [7, 3, 7]], dtype=int32)>

In [6]:
tensor1+tensor2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4,  8, 10],
       [ 8,  7, 15],
       [10,  5, 13]], dtype=int32)>

In [7]:
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 49,  23,  55],
       [ 92,  44, 103],
       [ 63,  37,  74]], dtype=int32)>

In [8]:
tensor1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 3, 4],
       [2, 5, 8],
       [3, 2, 6]], dtype=int32)>

In [9]:
tensor1*tensor2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 3, 15, 24],
       [12, 10, 56],
       [21,  6, 42]], dtype=int32)>

In [10]:
tensor1@tensor2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 49,  23,  55],
       [ 92,  44, 103],
       [ 63,  37,  74]], dtype=int32)>

## @ used For Matrix Multiplication

In [11]:
tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 49,  23,  55],
       [ 92,  44, 103],
       [ 63,  37,  74]], dtype=int32)>

In [12]:
tensor1@tensor2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 49,  23,  55],
       [ 92,  44, 103],
       [ 63,  37,  74]], dtype=int32)>

In [20]:
tensor3= tf.constant([
                      [1,4,4],[5,7,4],[9,6,4]
])



In [21]:
tensor4 = tf.constant([
                       [4,5,3],[7,8,3],[7,3,2]
])


In [22]:
# tensor3@tensor4
tf.matmul(tensor3, tensor4)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 60,  49,  23],
       [ 97,  93,  44],
       [106, 105,  53]], dtype=int32)>

In [23]:
tensor3*tensor4

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4, 20, 12],
       [35, 56, 12],
       [63, 18,  8]], dtype=int32)>