In [1]:
import tensorflow as tf
import numpy as np

#MATRIX MULTIPLICATION

In [2]:
matrix1= tf.constant([
                      [1,3],[4,5],[5,5]
])


In [3]:
matrix2= tf.constant([
                      [5,6],[0,8],[4,7]
])

In [4]:
matrix1+matrix2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  9],
       [ 4, 13],
       [ 9, 12]], dtype=int32)>

In [6]:
tf.matmul(tf.transpose(matrix1),matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 73],
       [35, 93]], dtype=int32)>

In [12]:
tf.reshape(matrix1,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 4],
       [5, 5, 5]], dtype=int32)>

In [15]:
tf.matmul(matrix1,tf.transpose(matrix2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[23, 24, 25],
       [50, 40, 51],
       [55, 40, 55]], dtype=int32)>

In [16]:
matrix1.shape , matrix2.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [17]:
tf.reshape(matrix2, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[5, 6, 0],
       [8, 4, 7]], dtype=int32)>

In [18]:
tf.matmul(matrix1, tf.reshape(matrix2, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[29, 18, 21],
       [60, 44, 35],
       [65, 50, 35]], dtype=int32)>

In [19]:
matrix3 = tf.constant([
                       [2,3],[4,5],[4,2]
])


In [20]:
matrix4 = tf.constant([
                       [3,4],[7,8],[2,5]
])

In [22]:
tf.matmul(matrix3,tf.reshape(matrix4, shape=(2,3) ))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[30, 14, 29],
       [52, 26, 53],
       [28, 20, 38]], dtype=int32)>

In [23]:
matrix3.shape, matrix4.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [25]:
matrix3 @ tf.reshape(matrix4, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[30, 14, 29],
       [52, 26, 53],
       [28, 20, 38]], dtype=int32)>

In [26]:
matrix3 * matrix4

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6, 12],
       [28, 40],
       [ 8, 10]], dtype=int32)>

In [27]:
matrix3[:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [28]:
matrix1[:-1]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 5]], dtype=int32)>

In [29]:
matrix1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 5],
       [5, 5]], dtype=int32)>

In [31]:
matrix1[...]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 5],
       [5, 5]], dtype=int32)>

In [32]:
matrix5 = matrix1[..., tf.newaxis]

In [33]:
matrix5

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [3]],

       [[4],
        [5]],

       [[5],
        [5]]], dtype=int32)>

In [34]:
matrix6 = tf.expand_dims(matrix5,axis=1)

In [35]:
matrix6

<tf.Tensor: shape=(3, 1, 2, 1), dtype=int32, numpy=
array([[[[1],
         [3]]],


       [[[4],
         [5]]],


       [[[5],
         [5]]]], dtype=int32)>

In [36]:
matrix6

<tf.Tensor: shape=(3, 1, 2, 1), dtype=int32, numpy=
array([[[[1],
         [3]]],


       [[[4],
         [5]]],


       [[[5],
         [5]]]], dtype=int32)>

In [40]:
matrix2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [0, 8],
       [4, 7]], dtype=int32)>

In [41]:
tf.transpose(matrix2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[5, 0, 4],
       [6, 8, 7]], dtype=int32)>