In [1]:
import tensorflow as tf
import numpy as np

#Matrix Multiplication Part 3

In [2]:
matrix1= tf.constant([
                      [1,4],[5,7],[8,3]
])

In [3]:
matrix2= tf.constant([
                      [1,6],[2,5],[5,2]
])


In [4]:
# tf.matmul(matrix1,matrix2)

InvalidArgumentError: ignored

In [5]:
tf.matmul(tf.transpose(matrix1), matrix2 )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[51, 47],
       [33, 65]], dtype=int32)>

In [8]:
tf.tensordot(tf.transpose(matrix1),matrix2, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[51, 47],
       [33, 65]], dtype=int32)>

In [9]:
tf.transpose(matrix2).shape , matrix1.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [10]:
tf.reshape(matrix1, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 4, 5],
       [7, 8, 3]], dtype=int32)>

In [13]:
matrix1.shape , matrix2.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [14]:
matrix1.ndim

2

In [15]:
matrix1.dtype

tf.int32