In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor_A = tf.range(1,33)
tensor_A

<tf.Tensor: shape=(32,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
      dtype=int32)>

In [3]:
tf.square(tensor_A)

<tf.Tensor: shape=(32,), dtype=int32, numpy=
array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024],
      dtype=int32)>

In [5]:
# tf.sqrt(tensor_A)
tf.sqrt(tf.cast(tensor_A, dtype=tf.float32))

<tf.Tensor: shape=(32,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 2.9999998 , 3.1622777 ,
       3.3166244 , 3.4641016 , 3.6055508 , 3.7416573 , 3.8729832 ,
       3.9999998 , 4.1231055 , 4.2426405 , 4.3588986 , 4.472136  ,
       4.5825753 , 4.6904154 , 4.795831  , 4.898979  , 5.        ,
       5.0990195 , 5.196152  , 5.2915025 , 5.3851647 , 5.477226  ,
       5.5677643 , 5.6568537 ], dtype=float32)>

In [7]:
tf.math.log(tf.cast(tensor_A, dtype=tf.float32))

<tf.Tensor: shape=(32,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574, 2.7080503, 2.7725887, 2.8332133, 2.8903718,
       2.944439 , 2.9957323, 3.0445225, 3.0910425, 3.1354942, 3.1780539,
       3.218876 , 3.2580965, 3.295837 , 3.3322046, 3.3672957, 3.4011974,
       3.4339871, 3.465736 ], dtype=float32)>

In [8]:
tf.abs(tensor_A)

<tf.Tensor: shape=(32,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
      dtype=int32)>

In [13]:
tf.math.add(tensor_A,10)

<tf.Tensor: shape=(32,), dtype=int32, numpy=
array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
      dtype=int32)>

In [14]:
tf.math.add_n(tensor_A,10)

<tf.Tensor: shape=(), dtype=int32, numpy=528>

In [16]:
tf.math.angle(tf.cast(tensor_A, dtype=tf.float32))

<tf.Tensor: shape=(32,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>

In [17]:
tf.math.argmax(tensor_A)

<tf.Tensor: shape=(), dtype=int64, numpy=31>

In [18]:
tf.math.argmin(tensor_A)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [21]:
tf.math.rsqrt(tf.cast(tensor_A, dtype=tf.float32))

<tf.Tensor: shape=(32,), dtype=float32, numpy=
array([0.99999994, 0.7071067 , 0.57735026, 0.49999997, 0.4472136 ,
       0.40824828, 0.37796447, 0.35355335, 0.3333333 , 0.31622776,
       0.30151132, 0.28867513, 0.27735007, 0.26726124, 0.2581989 ,
       0.24999999, 0.2425356 , 0.23570225, 0.22941573, 0.2236068 ,
       0.21821786, 0.2132007 , 0.2085144 , 0.20412414, 0.2       ,
       0.19611613, 0.19245008, 0.18898223, 0.18569534, 0.1825742 ,
       0.1796053 , 0.17677668], dtype=float32)>