Other Way To Create Tensor

In [2]:
import numpy as np
import tensorflow as tf

In [9]:
numpy_A = np.arange(1,23, dtype= np.int32)
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22], dtype=int32)

In [10]:
tf.ones([10,4])

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [14]:
tf.zeros(shape=(1,2))

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [15]:
A = tf.constant(numpy_A)

A

<tf.Tensor: shape=(22,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22], dtype=int32)>

In [16]:
numpy_B = np.arange(1,14  , dtype= np.int16)

In [17]:
numpy_B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13], dtype=int16)

In [18]:
tensor_B = tf.constant(numpy_B)

tensor_B

<tf.Tensor: shape=(13,), dtype=int16, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13], dtype=int16)>

In [ ]:
numpy_B == tensor_B

<tf.Tensor: shape=(13,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])>