In [1]:
import tensorflow as tf
import numpy as np

In [4]:
listes= [1,2,3,4,5,6,7]
tf.one_hot(listes, depth=8)

<tf.Tensor: shape=(7, 8), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [5]:
iset =  [2,3,5,7,8,3,1]
one_hot_values = tf.one_hot(iset, depth=6, on_value=1234, off_value=2233)
one_hot_values

<tf.Tensor: shape=(7, 6), dtype=int32, numpy=
array([[2233, 2233, 1234, 2233, 2233, 2233],
       [2233, 2233, 2233, 1234, 2233, 2233],
       [2233, 2233, 2233, 2233, 2233, 1234],
       [2233, 2233, 2233, 2233, 2233, 2233],
       [2233, 2233, 2233, 2233, 2233, 2233],
       [2233, 2233, 2233, 1234, 2233, 2233],
       [2233, 1234, 2233, 2233, 2233, 2233]], dtype=int32)>

In [7]:
liss  = [2,3,4,5,6,8,9]
tf.one_hot(liss, depth=5, off_value=111, on_value=000, dtype=tf.int32)


<tf.Tensor: shape=(7, 5), dtype=int32, numpy=
array([[111, 111,   0, 111, 111],
       [111, 111, 111,   0, 111],
       [111, 111, 111, 111,   0],
       [111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111]], dtype=int32)>