##Practices##


In [1]:
import tensorflow as tf
import numpy as np

In [3]:
scalar = tf.constant(0,1)
scalar

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([[0,1]])
vector

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>

In [6]:
vector.ndim

2

In [7]:
matrix = tf.constant([[0,1],[2,3],[4,5]])
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3],
       [4, 5]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
tensor = tf.constant([
                      [0,1],[1,2],[3,4],[4,6],[7,8],[9,0]
], dtype=tf.int16)

tensor

<tf.Tensor: shape=(6, 2), dtype=int16, numpy=
array([[0, 1],
       [1, 2],
       [3, 4],
       [4, 6],
       [7, 8],
       [9, 0]], dtype=int16)>

In [10]:
tensor.ndim

2

In [15]:
variable = tf.Variable(
                        [0,1]
                        )
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([0, 1], dtype=int32)>

In [16]:
variable[0].assign(5)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 1], dtype=int32)>

In [17]:
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 1], dtype=int32)>

In [18]:
constant = tf.constant([0,1])
constant

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

In [19]:
constant==variable

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

##Random

In [20]:
random = tf.random.Generator.from_seed(42)
random = random.normal(shape=(1,2))

random

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.7565803 , -0.06854702]], dtype=float32)>

In [21]:
random2 = tf.random.Generator.from_seed(42)
random2 = random2.uniform(shape=(1,2))

random2

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.7493447 , 0.73561966]], dtype=float32)>

In [23]:
random==random2

<tf.Tensor: shape=(1, 2), dtype=bool, numpy=array([[False, False]])>

#Shuffle

In [33]:

tf.random.set_seed(42)

not_shuffled = tf.random.shuffle([
                                  [1,2],[3,4],[5,6]
] ,seed=42)

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([23,  1], dtype=int32)>

#NUMPY

In [34]:
numpy_A = np.arange(1,23, dtype=np.int16)

In [35]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22], dtype=int16)

In [36]:
tensor_A = tf.constant(numpy_A)

In [37]:
tensor_A

<tf.Tensor: shape=(22,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22], dtype=int16)>

In [38]:
numpy_A==tensor_A

<tf.Tensor: shape=(22,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])>

In [39]:
tensor_A = tf.constant(numpy_A, shape=(11,2))

In [40]:
tensor_A

<tf.Tensor: shape=(11, 2), dtype=int16, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22]], dtype=int16)>

##GETTING INFORMATION FROM USER ##

In [43]:
Info = tf.ones(4,3,5)

In [44]:
Info

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 1, 1, 1], dtype=int32)>

In [45]:
Info = tf.ones(shape=(1,2,4))

In [46]:
Info

<tf.Tensor: shape=(1, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [50]:
Info.set_shape=(5)

In [51]:
Info

<tf.Tensor: shape=(1, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [53]:
print(Info.ndim)
print(Info.shape)
print(Info.dtype)
print(Info.shape[0])
print(Info.shape[-1])
print(tf.size(Info))
print(tf.size(Info).numpy())

3
(1, 2, 4)
<dtype: 'float32'>
1
4
tf.Tensor(8, shape=(), dtype=int32)
8
