#Tf.constant

In [2]:
import tensorflow as tf
import numpy as np
import tensorflow_probability as tfp

In [3]:
scalar = tf.constant(10,4)
scalar

<tf.Tensor: shape=(), dtype=uint8, numpy=10>

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

TensorShape([])

In [6]:
vector = tf.constant([10,5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5], dtype=int32)>

In [7]:
vector.shape

TensorShape([2])

In [8]:
vector.ndim

1

In [9]:
matrix = tf.constant([[10,7],[8,5],[9,2],[5,2]])
matrix

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  5],
       [ 9,  2],
       [ 5,  2]], dtype=int32)>

In [10]:
matrix.shape

TensorShape([4, 2])

In [11]:
matrix.ndim

2

In [12]:
tensor = tf.constant([
                      [10,4],[5,6],[6,4],[7,5],[7,3],[8,9],[1,6],[8,2],[7,2],[8,3],[2,6],[7,3],[5,1],[7,3],[4,8],[3,7]
])
tensor

<tf.Tensor: shape=(16, 2), dtype=int32, numpy=
array([[10,  4],
       [ 5,  6],
       [ 6,  4],
       [ 7,  5],
       [ 7,  3],
       [ 8,  9],
       [ 1,  6],
       [ 8,  2],
       [ 7,  2],
       [ 8,  3],
       [ 2,  6],
       [ 7,  3],
       [ 5,  1],
       [ 7,  3],
       [ 4,  8],
       [ 3,  7]], dtype=int32)>

In [13]:
tensor.ndim

2

In [14]:
tensor.shape

TensorShape([16, 2])

In [15]:
tensor

<tf.Tensor: shape=(16, 2), dtype=int32, numpy=
array([[10,  4],
       [ 5,  6],
       [ 6,  4],
       [ 7,  5],
       [ 7,  3],
       [ 8,  9],
       [ 1,  6],
       [ 8,  2],
       [ 7,  2],
       [ 8,  3],
       [ 2,  6],
       [ 7,  3],
       [ 5,  1],
       [ 7,  3],
       [ 4,  8],
       [ 3,  7]], dtype=int32)>

In [16]:
tensor.dtype

tf.int32

In [17]:
tensor.shape[0]

16

In [19]:
tensor.shape[1]

2

#Tf.Variable

In [20]:
var = tf.Variable([10,8])
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>

In [22]:
var[0].assign(4)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 8], dtype=int32)>

In [23]:
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 8], dtype=int32)>

In [24]:
var2 = tf.Variable(10,2)
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [27]:
var2.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=2>

In [28]:
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

#Random

In [29]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(2,3))
random_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [30]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(2,4))
random_2

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],
      dtype=float32)>

In [31]:
random_1==random_2

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [33]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.uniform(shape=(2,4))
random_3

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794, 0.49039817],
       [0.1889317 , 0.52027524, 0.8736881 , 0.46921718]], dtype=float32)>

In [34]:
random_2==random_3

<tf.Tensor: shape=(2, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False]])>

#Shuffle

In [35]:
not_shuffled = tf.constant([
                            [10,4],[5,6],[7,4]
])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  4],
       [ 5,  6],
       [ 7,  4]], dtype=int32)>

In [43]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  6],
       [10,  4],
       [ 7,  4]], dtype=int32)>

In [47]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  4],
       [ 5,  6],
       [ 7,  4]], dtype=int32)>

#Numpy

In [55]:
numpy_A = np.arange(1,23, dtype=np.float32)
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22.], dtype=float32)

In [56]:
numpy_B = np.arange(1,30, dtype=np.float16)
numpy_B

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29.], dtype=float16)

In [58]:
tensor_B = tf.constant(numpy_B)
tensor_B

<tf.Tensor: shape=(29,), dtype=float16, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29.], dtype=float16)>

In [59]:
numpy_B==tensor_B

<tf.Tensor: shape=(29,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])>

In [60]:
tf.zeros([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [61]:
tf.ones([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [65]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(22,), dtype=float32, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22.], dtype=float32)>

In [69]:
tensor_A

<tf.Tensor: shape=(22,), dtype=float32, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22.], dtype=float32)>

In [70]:
matrix = tf.zeros(shape=(1,3,4))
matrix

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [71]:
print(matrix.dtype)
print(matrix.shape)
print(matrix.ndim)
print(matrix.shape[0])
print(matrix.shape[-1])
print(tf.size(matrix))
print(tf.size(matrix).numpy())


<dtype: 'float32'>
(1, 3, 4)
3
1
4
tf.Tensor(12, shape=(), dtype=int32)
12


In [72]:
matrix

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [73]:
matrix[:2]

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [75]:
matrix = tf.constant([[10,3],[4,5],[5,2],[5,6],[6,3],[5,6]])
matrix

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[10,  3],
       [ 4,  5],
       [ 5,  2],
       [ 5,  6],
       [ 6,  3],
       [ 5,  6]], dtype=int32)>

In [76]:
matrix[:1]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  3]], dtype=int32)>

In [77]:
matrix[:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [ 4,  5]], dtype=int32)>

In [79]:
matrix_2 = matrix[...,tf.newaxis]
matrix_2

<tf.Tensor: shape=(6, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 5],
        [ 2]],

       [[ 5],
        [ 6]],

       [[ 6],
        [ 3]],

       [[ 5],
        [ 6]]], dtype=int32)>

In [80]:
tf.expand_dims(matrix,axis=1)

<tf.Tensor: shape=(6, 1, 2), dtype=int32, numpy=
array([[[10,  3]],

       [[ 4,  5]],

       [[ 5,  2]],

       [[ 5,  6]],

       [[ 6,  3]],

       [[ 5,  6]]], dtype=int32)>

In [81]:
matrix+10

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[20, 13],
       [14, 15],
       [15, 12],
       [15, 16],
       [16, 13],
       [15, 16]], dtype=int32)>

In [82]:
matrix-10

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 0, -7],
       [-6, -5],
       [-5, -8],
       [-5, -4],
       [-4, -7],
       [-5, -4]], dtype=int32)>

In [83]:
matrix*10

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[100,  30],
       [ 40,  50],
       [ 50,  20],
       [ 50,  60],
       [ 60,  30],
       [ 50,  60]], dtype=int32)>

In [84]:
matrix/10

<tf.Tensor: shape=(6, 2), dtype=float64, numpy=
array([[1. , 0.3],
       [0.4, 0.5],
       [0.5, 0.2],
       [0.5, 0.6],
       [0.6, 0.3],
       [0.5, 0.6]])>

In [85]:
tf.math.add(matrix, 10)

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[20, 13],
       [14, 15],
       [15, 12],
       [15, 16],
       [16, 13],
       [15, 16]], dtype=int32)>

In [87]:
tf.math.subtract(matrix,10)

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 0, -7],
       [-6, -5],
       [-5, -8],
       [-5, -4],
       [-4, -7],
       [-5, -4]], dtype=int32)>

In [89]:
tf.matmul(matrix,matrix_2)

<tf.Tensor: shape=(6, 6, 1), dtype=int32, numpy=
array([[[109],
        [ 55],
        [ 56],
        [ 68],
        [ 69],
        [ 68]],

       [[ 55],
        [ 41],
        [ 30],
        [ 50],
        [ 39],
        [ 50]],

       [[ 56],
        [ 30],
        [ 29],
        [ 37],
        [ 36],
        [ 37]],

       [[ 68],
        [ 50],
        [ 37],
        [ 61],
        [ 48],
        [ 61]],

       [[ 69],
        [ 39],
        [ 36],
        [ 48],
        [ 45],
        [ 48]],

       [[ 68],
        [ 50],
        [ 37],
        [ 61],
        [ 48],
        [ 61]]], dtype=int32)>

In [90]:
vector_1 = tf.constant([
                        [1,3],[5,3],[4,5]
])
vector_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [5, 3],
       [4, 5]], dtype=int32)>

In [92]:
vector_2 = tf.constant([
                        [1,4],[6,3],[6,2]
])
vector_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [6, 3],
       [6, 2]], dtype=int32)>

In [93]:
vector_1==vector_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True, False],
       [False,  True],
       [False, False]])>

In [94]:
# tf.matmul(vector_1,vector_2)

InvalidArgumentError: ignored

In [95]:
tf.matmul(tf.transpose(vector_1),vector_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[55, 27],
       [51, 31]], dtype=int32)>

In [96]:
tf.matmul(vector_1,tf.transpose(vector_2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 15, 12],
       [17, 39, 36],
       [24, 39, 34]], dtype=int32)>

In [97]:
vector_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [5, 3],
       [4, 5]], dtype=int32)>

In [99]:
tf.cast(vector_1,dtype=tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 3.],
       [5., 3.],
       [4., 5.]], dtype=float16)>

In [100]:
tf.cast(vector_2,dtype=tf.float32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [6., 3.],
       [6., 2.]], dtype=float32)>

In [101]:
vector_1==vector_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True, False],
       [False,  True],
       [False, False]])>

In [103]:
tf.tensordot(tf.transpose(vector_1),vector_2, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[55, 27],
       [51, 31]], dtype=int32)>

In [104]:
tf.reduce_max(vector_1)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [105]:
tf.reduce_min(vector_1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [106]:
tf.reduce_mean(vector_1)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [107]:
tf.reduce_sum(vector_1)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [109]:
tf.reduce_mean(vector_1)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [111]:
tf.math.reduce_variance(tf.cast(vector_1, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=1.917>

In [112]:
tf.math.reduce_std(tf.cast(vector_1,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1.3844373>

In [113]:
tf.argmax(vector_1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 2])>

In [116]:
# vector_1[tf.argmax(vector_1)]

TypeError: ignored