#Practices

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
scalar = tf.constant(2,4)
scalar

<tf.Tensor: shape=(), dtype=uint8, numpy=2>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([1,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[1,3],[4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 5]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
tensor = tf.constant([
                      [1,3],[5,6],[8,4],[6,3],[6,4]
])
tensor

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[1, 3],
       [5, 6],
       [8, 4],
       [6, 3],
       [6, 4]], dtype=int32)>

In [9]:
tensor.ndim

2

#Variable

In [10]:
var = tf.Variable([1,3])
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 3], dtype=int32)>

In [12]:
var[0].assign(5)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 3], dtype=int32)>

#Random Tensor

In [16]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(1,3))
random_1

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.7565803 , -0.06854702,  0.07595026]], dtype=float32)>

In [17]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(1,3))
random_2

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.7493447 , 0.73561966, 0.45230794]], dtype=float32)>

In [18]:
random_1==random_2

<tf.Tensor: shape=(1, 3), dtype=bool, numpy=array([[False, False, False]])>

#Shuffle

In [19]:
not_shuffled = tf.constant([
                            [2,4],[5,3],[5,2],[6,4],[5,9]
])
not_shuffled

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 3],
       [5, 2],
       [6, 4],
       [5, 9]], dtype=int32)>

In [20]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 3],
       [5, 2],
       [2, 4],
       [6, 4],
       [5, 9]], dtype=int32)>

In [21]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 2],
       [5, 3],
       [6, 4],
       [5, 9],
       [2, 4]], dtype=int32)>

In [22]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 2],
       [2, 4],
       [5, 9],
       [6, 4],
       [5, 3]], dtype=int32)>

#NUMPY

In [24]:
tf.zeros(shape=(1,3))

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 0.]], dtype=float32)>

In [25]:
tf.ones(shape=(1,3))

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>

In [26]:
numpy_A = np.arange(1,23, dtype=np.int16)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22], dtype=int16)

In [27]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(22,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22], dtype=int16)>

In [28]:
tensor_A

<tf.Tensor: shape=(22,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22], dtype=int16)>

In [30]:
print(tensor_A.dtype)
print(tensor_A.shape)
print(tensor_A.ndim)
print(tensor_A.shape[0])
print(tensor_A.shape[-1])
print(tf.size(tensor_A))
print(tf.size(tensor_A).numpy())

<dtype: 'int16'>
(22,)
1
22
22
tf.Tensor(22, shape=(), dtype=int32)
22


In [31]:
tensor_A

<tf.Tensor: shape=(22,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22], dtype=int16)>

In [32]:
tensor_A[:2]

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 2], dtype=int16)>

In [33]:
tensor_A[:-1]

<tf.Tensor: shape=(21,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21], dtype=int16)>

In [34]:
tensor_B = tensor_A[...,tf.newaxis]
tensor_B

<tf.Tensor: shape=(22, 1), dtype=int16, numpy=
array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22]], dtype=int16)>

In [36]:
tf.expand_dims(tensor_B, axis=1)

<tf.Tensor: shape=(22, 1, 1), dtype=int16, numpy=
array([[[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]]], dtype=int16)>

In [37]:
tensor_A

<tf.Tensor: shape=(22,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22], dtype=int16)>

In [38]:
tensor_A +10

<tf.Tensor: shape=(22,), dtype=int16, numpy=
array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32], dtype=int16)>

In [39]:
tensor_A-10

<tf.Tensor: shape=(22,), dtype=int16, numpy=
array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12], dtype=int16)>

In [40]:
tensor_A *10

<tf.Tensor: shape=(22,), dtype=int16, numpy=
array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220], dtype=int16)>

In [41]:
tensor_A/10

<tf.Tensor: shape=(22,), dtype=float32, numpy=
array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2], dtype=float32)>

In [42]:
tensor_A**10

<tf.Tensor: shape=(22,), dtype=int16, numpy=
array([     1,   1024,  -6487,      0,    761, -23552,  15089,      0,
         7057,  -7168, -20263,      0, -23095, -15360, -21407,      0,
       -21087,  17408, -15991,      0,  28441,  25600], dtype=int16)>

In [43]:
tf.math.add(tensor_A, 10)

<tf.Tensor: shape=(22,), dtype=int16, numpy=
array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32], dtype=int16)>

In [44]:
tf.math.subtract(tensor_A, 10)

<tf.Tensor: shape=(22,), dtype=int16, numpy=
array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12], dtype=int16)>

In [45]:
tf.math.multiply(tensor_A, 10)

<tf.Tensor: shape=(22,), dtype=int16, numpy=
array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220], dtype=int16)>

In [46]:
tf.math.divide(tensor_A, 10)

<tf.Tensor: shape=(22,), dtype=float32, numpy=
array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2], dtype=float32)>

In [47]:
matrix_1 = [1,3,4,5,6,4,12,3]
matrix_1

[1, 3, 4, 5, 6, 4, 12, 3]

In [48]:
matrix_2 = [2,1,3,6,4,14,4,10,1]
matrix_2

[2, 1, 3, 6, 4, 14, 4, 10, 1]

In [55]:
matrix_1 = tf.constant([
                        [1,3],[4,2],[4,9]
])
matrix_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 2],
       [4, 9]], dtype=int32)>

In [56]:
matrix_2 = tf.constant([
                        [2,4],[7,5],[6,4]
])
matrix_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 4],
       [7, 5],
       [6, 4]], dtype=int32)>

In [58]:
tf.matmul(tf.transpose(matrix_1),matrix_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[54, 40],
       [74, 58]], dtype=int32)>

In [60]:
tf.matmul(tf.reshape(matrix_1, shape=(2,3)), matrix_2  )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[47, 35],
       [86, 64]], dtype=int32)>

In [61]:
matrix_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 2],
       [4, 9]], dtype=int32)>

In [62]:
tf.cast(matrix_1, dtype=tf.float16)


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 3.],
       [4., 2.],
       [4., 9.]], dtype=float16)>

In [63]:
tf.cast(matrix_2, dtype=tf.float32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 4.],
       [7., 5.],
       [6., 4.]], dtype=float32)>

In [65]:
matrix_3 =tf.constant([
                       [-2,-4],[-5,-3],[-7,-4],[-5,-1],[-7,-3]
])
matrix_3

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[-2, -4],
       [-5, -3],
       [-7, -4],
       [-5, -1],
       [-7, -3]], dtype=int32)>

In [66]:
tf.abs(matrix_3)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 3],
       [7, 4],
       [5, 1],
       [7, 3]], dtype=int32)>

In [67]:
matrix_3

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[-2, -4],
       [-5, -3],
       [-7, -4],
       [-5, -1],
       [-7, -3]], dtype=int32)>

In [68]:
E= tf.constant(np.random.randint(1,30, size=10))
E

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([16, 16, 29, 22, 13, 29, 22,  7, 13, 27])>

In [69]:
print(tf.reduce_min(E))
print(tf.reduce_max(E))
print(tf.reduce_mean(E))
print(tf.reduce_sum(E))

tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(29, shape=(), dtype=int64)
tf.Tensor(19, shape=(), dtype=int64)
tf.Tensor(194, shape=(), dtype=int64)
