# **Squueze, One_Hot, More_Math & Tensor_To_Numpy and Vice_Versa**

In [3]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [8]:
squeezed = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))

In [9]:
squeezed

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.13453805, 0.8309562 , 0.21159518, 0.7079952 , 0.13053131,
           0.9921111 , 0.1933285 , 0.94919276, 0.98095214, 0.46813238,
           0.3937211 , 0.7493992 , 0.40820312, 0.5316434 , 0.89649475,
           0.3511412 , 0.4099766 , 0.458171  , 0.25448442, 0.44487107,
           0.03128815, 0.4141121 , 0.7906476 , 0.25770319, 0.5064589 ,
           0.7176956 , 0.7951691 , 0.6575737 , 0.33162737, 0.4968245 ,
           0.9098575 , 0.41048658, 0.33443856, 0.9865961 , 0.89107084,
           0.39430368, 0.5542927 , 0.11357927, 0.90586925, 0.88669133,
           0.7413019 , 0.30418324, 0.4685862 , 0.4217937 , 0.14775729,
           0.15892732, 0.22329605, 0.02586496, 0.9330965 , 0.97399855]]]]],
      dtype=float32)>

In [10]:
squeezed_value = tf.squeeze(squeezed)

In [11]:
squeezed_value

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.13453805, 0.8309562 , 0.21159518, 0.7079952 , 0.13053131,
       0.9921111 , 0.1933285 , 0.94919276, 0.98095214, 0.46813238,
       0.3937211 , 0.7493992 , 0.40820312, 0.5316434 , 0.89649475,
       0.3511412 , 0.4099766 , 0.458171  , 0.25448442, 0.44487107,
       0.03128815, 0.4141121 , 0.7906476 , 0.25770319, 0.5064589 ,
       0.7176956 , 0.7951691 , 0.6575737 , 0.33162737, 0.4968245 ,
       0.9098575 , 0.41048658, 0.33443856, 0.9865961 , 0.89107084,
       0.39430368, 0.5542927 , 0.11357927, 0.90586925, 0.88669133,
       0.7413019 , 0.30418324, 0.4685862 , 0.4217937 , 0.14775729,
       0.15892732, 0.22329605, 0.02586496, 0.9330965 , 0.97399855],
      dtype=float32)>

In [12]:
val2 = tf.constant(tf.random.uniform(shape=[20]), shape=(1,1,1,1,20))
val2

<tf.Tensor: shape=(1, 1, 1, 1, 20), dtype=float32, numpy=
array([[[[[0.48509288, 0.3381312 , 0.11808431, 0.28704894, 0.76382387,
           0.2705257 , 0.5498915 , 0.36231887, 0.47563815, 0.38060212,
           0.15691268, 0.7117622 , 0.8478862 , 0.5927402 , 0.59476507,
           0.3481511 , 0.82513297, 0.7233238 , 0.38479745, 0.32314503]]]]],
      dtype=float32)>

In [14]:
val2_vale = tf.squeeze(val2)
val2_vale

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0.48509288, 0.3381312 , 0.11808431, 0.28704894, 0.76382387,
       0.2705257 , 0.5498915 , 0.36231887, 0.47563815, 0.38060212,
       0.15691268, 0.7117622 , 0.8478862 , 0.5927402 , 0.59476507,
       0.3481511 , 0.82513297, 0.7233238 , 0.38479745, 0.32314503],
      dtype=float32)>

In [16]:
vall = tf.constant([
                     [2,4],[5,3],[5,7],[8,6]
])
vall

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 3],
       [5, 7],
       [8, 6]], dtype=int32)>

In [17]:
tf.one_hot(vall, depth=5)

<tf.Tensor: shape=(4, 2, 5), dtype=float32, numpy=
array([[[0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [18]:
tf.one_hot(vall, depth=4, on_value = 'I am On value', off_value='I am Off value')

<tf.Tensor: shape=(4, 2, 4), dtype=string, numpy=
array([[[b'I am Off value', b'I am Off value', b'I am On value',
         b'I am Off value'],
        [b'I am Off value', b'I am Off value', b'I am Off value',
         b'I am Off value']],

       [[b'I am Off value', b'I am Off value', b'I am Off value',
         b'I am Off value'],
        [b'I am Off value', b'I am Off value', b'I am Off value',
         b'I am On value']],

       [[b'I am Off value', b'I am Off value', b'I am Off value',
         b'I am Off value'],
        [b'I am Off value', b'I am Off value', b'I am Off value',
         b'I am Off value']],

       [[b'I am Off value', b'I am Off value', b'I am Off value',
         b'I am Off value'],
        [b'I am Off value', b'I am Off value', b'I am Off value',
         b'I am Off value']]], dtype=object)>

In [20]:
tf.math.log(tf.cast(vall, dtype=tf.float32))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.6931472, 1.3862944],
       [1.609438 , 1.0986123],
       [1.609438 , 1.9459102],
       [2.0794415, 1.7917595]], dtype=float32)>

In [21]:
tf.math.sin(tf.cast(vall, dtype=tf.float32))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.9092974 , -0.7568025 ],
       [-0.9589243 ,  0.14112   ],
       [-0.9589243 ,  0.6569866 ],
       [ 0.98935825, -0.2794155 ]], dtype=float32)>

In [22]:
tf.math.cos(tf.cast(vall, dtype=tf.float32))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.4161468 , -0.6536436 ],
       [ 0.28366217, -0.9899925 ],
       [ 0.28366217,  0.75390226],
       [-0.14550003,  0.96017027]], dtype=float32)>

In [23]:
numpy_A  = tf.constant(np.array([[1,3],[4,3]]))
numpy_A

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 3],
       [4, 3]])>

In [24]:
tensor_A = tf.constant([[1,3],[4,3]])
tensor_A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 3]], dtype=int32)>

In [25]:
numpy_A.dtype, tensor_A.dtype

(tf.int64, tf.int32)