# **Tensor and Numpy Practices**

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
scalar = tf.constant(1,4)
scalar

<tf.Tensor: shape=(), dtype=uint8, numpy=1>

In [3]:
scalar.ndim

0

In [5]:
scalar2 = tf.constant([[1,2], [3,4]])
scalar2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [6]:
scalar2.ndim

2

In [7]:
scalar3 = tf.constant([[1,1], [3,4], [5,6], [6,7], [8,9]])
scalar3

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[1, 1],
       [3, 4],
       [5, 6],
       [6, 7],
       [8, 9]], dtype=int32)>

In [8]:
scalar3.ndim

2

In [9]:
vector = tf.constant([
                      [1,2],[3,4],[5,6],[7,8],[9,0],[0,1],[1,0],[1,1],[2,3],
])

vector

<tf.Tensor: shape=(9, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0],
       [0, 1],
       [1, 0],
       [1, 1],
       [2, 3]], dtype=int32)>

In [10]:
vector.ndim

2

In [18]:
another_matrix = tf.Variable([[1,2]])
another_matrix


<tf.Variable 'Variable:0' shape=(1, 2) dtype=int32, numpy=array([[1, 2]], dtype=int32)>

In [20]:
another = tf.Variable([[1,2]])
another

<tf.Variable 'Variable:0' shape=(1, 2) dtype=int32, numpy=array([[1, 2]], dtype=int32)>

In [21]:
variable = tf.Variable([[1,3]])
variable

<tf.Variable 'Variable:0' shape=(1, 2) dtype=int32, numpy=array([[1, 3]], dtype=int32)>

In [27]:
random1= tf.random.Generator.from_seed(42)
random1 = random1.normal(shape =(2,3))
random1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [28]:
random2 = tf.random.Generator.from_seed(32)
random2 = random2.uniform(shape = (3,3))
random2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.20822704, 0.07357836, 0.88440466],
       [0.17085445, 0.42289293, 0.9806658 ],
       [0.43658388, 0.13378775, 0.11820638]], dtype=float32)>

In [30]:
random1==random2

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [36]:
not_shuffled = tf.constant([[1,2],[4,5],[6,7]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [6, 7]], dtype=int32)>

In [37]:
not_shuffled = tf.Variable([
                            [1,2],[3,4],[5,6],[7,8],[9,0]
  ])

not_shuffled

<tf.Variable 'Variable:0' shape=(5, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]], dtype=int32)>

In [38]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8],
       [3, 4],
       [1, 2],
       [9, 0]], dtype=int32)>

In [41]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6],
       [9, 0]], dtype=int32)>

In [42]:
tf.ones([1,3])

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>

In [44]:
numpy_A = np.arange(1,25)

In [45]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [47]:
numpy_B = np.arange(2,20 ,dtype=np.int32)

In [48]:
numpy_B

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19], dtype=int32)

In [49]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [50]:
tensor_B = tf.constant(numpy_B)
tensor_B

<tf.Tensor: shape=(18,), dtype=int32, numpy=
array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19], dtype=int32)>

In [53]:
tensor_A==tensor_B

<tf.Tensor: shape=(18,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])>

In [54]:
tensor_B

<tf.Tensor: shape=(18,), dtype=int32, numpy=
array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19], dtype=int32)>

In [63]:
not_shuffled = tf.constant([
                            [2,3],[3,4],[5,7],[8,9],[5,3],[5,6]
 ])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[5, 6],
       [5, 3],
       [8, 9],
       [3, 4],
       [5, 7],
       [2, 3]], dtype=int32)>

In [65]:

not_shuffled = tf.constant([
                            [2,3],[3,4],[5,7],[8,9],[5,3],[5,6]
 ])

tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[8, 9],
       [5, 3],
       [3, 4],
       [5, 6],
       [5, 7],
       [2, 3]], dtype=int32)>

In [68]:
tensor = tf.Variable([
                      [1,2],[3,4],[5,6],
])

tensor

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [70]:
matrix = tf.constant([[1,3]], dtype=tf.int32)
matrix

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 3]], dtype=int32)>

In [72]:
scalar = tf.constant([
                      [1,3],[4,6],[7,9],[3,2]
], dtype= tf.int16 )

scalar


<tf.Tensor: shape=(4, 2), dtype=int16, numpy=
array([[1, 3],
       [4, 6],
       [7, 9],
       [3, 2]], dtype=int16)>

In [73]:
numpy_C = np.arange(1,23, dtype=np.int16)

numpy_C

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22], dtype=int16)

In [75]:
numpy_D = np.arange(1,10, dtype=np.int16)

numpy_D

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [76]:
numpy_C==numpy_D

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [77]:
tensor_D = tf.constant(numpy_D)
tensor_D

<tf.Tensor: shape=(9,), dtype=int16, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)>

In [78]:
tensor_D==numpy_D

<tf.Tensor: shape=(9,), dtype=bool, numpy=array([ True,  True,  True,  True,  True,  True,  True,  True,  True])>