#***Practices***

In [6]:
import tensorflow as tf
import numpy as np
import tensorflow_probability as tfp

#Tf.constant

In [7]:
scalar = tf.constant(10,2)
scalar

<tf.Tensor: shape=(), dtype=float64, numpy=10.0>

In [8]:
scalar.ndim

0

In [9]:
scalar.dtype

tf.float64

In [10]:
scalar.shape

TensorShape([])

In [12]:
vector = tf.constant([
                      [10,3],[4,5],[3,2]
])
vector

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  3],
       [ 4,  5],
       [ 3,  2]], dtype=int32)>

In [13]:
vector.ndim

2

In [14]:
vector.shape

TensorShape([3, 2])

In [15]:
vector.dtype

tf.int32

In [17]:
matrix= tf.constant([10,4])
matrix

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  4], dtype=int32)>

In [18]:
matrix.dtype

tf.int32

In [19]:
matrix.shape

TensorShape([2])

In [20]:
matrix.ndim

1

In [21]:
tensor = tf.constant([
                      [13,4],[5,2],[5,1],[6,7]
])
tensor

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[13,  4],
       [ 5,  2],
       [ 5,  1],
       [ 6,  7]], dtype=int32)>

In [22]:
tensor.ndim

2

In [23]:
tensor.dtype

tf.int32

In [24]:
tensor.shape

TensorShape([4, 2])

#Tf.variable

In [25]:
variable = tf.Variable([10,5])
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  5], dtype=int32)>

In [27]:
variable.dtype

tf.int32

In [28]:
variable.shape

TensorShape([2])

In [29]:
variable[0].assign(4)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [30]:
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [31]:
variable2 = tf.constant(10,4)
variable2

<tf.Tensor: shape=(), dtype=uint8, numpy=10>

#Random

In [45]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(2,4))
random_1

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],
      dtype=float32)>

In [48]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(2,4))
random_2

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794, 0.49039817],
       [0.1889317 , 0.52027524, 0.8736881 , 0.46921718]], dtype=float32)>

In [49]:
random_1 == random_2

<tf.Tensor: shape=(2, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False]])>

In [50]:
random_2

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794, 0.49039817],
       [0.1889317 , 0.52027524, 0.8736881 , 0.46921718]], dtype=float32)>

#Shuffle

In [51]:
not_shuffled = tf.constant([
                            [1,5],[6,4],[7,9]
])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 5],
       [6, 4],
       [7, 9]], dtype=int32)>

In [55]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 9],
       [1, 5],
       [6, 4]], dtype=int32)>

In [60]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 5],
       [6, 4],
       [7, 9]], dtype=int32)>

#NUMPY

In [64]:
numpy_A = np.arange(1,40, dtype=np.float16)
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
      dtype=float16)

In [66]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(39,), dtype=float16, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
      dtype=float16)>

In [67]:
numpy_B = np.arange(1,20,dtype=np.float16)
numpy_B

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.], dtype=float16)

In [69]:
tensor_B = tf.constant(numpy_B)
tensor_B

<tf.Tensor: shape=(19,), dtype=float16, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.], dtype=float16)>

#Getting Information

In [70]:
tensor_A

<tf.Tensor: shape=(39,), dtype=float16, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
      dtype=float16)>

In [71]:
print(tensor_A.dtype)
print(tensor_A.shape)
print(tensor_A.ndim)
print(tensor_A.shape[0])
print(tensor_A.shape[-1])
print(tf.size(tensor_A))
print(tf.size(tensor_A).numpy())

<dtype: 'float16'>
(39,)
1
39
39
tf.Tensor(39, shape=(), dtype=int32)
39


#Indexing

In [72]:
tensor_A

<tf.Tensor: shape=(39,), dtype=float16, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
      dtype=float16)>

In [73]:
tensor_A[:2]

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

In [74]:
tensor_A[:-1]

<tf.Tensor: shape=(38,), dtype=float16, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.],
      dtype=float16)>

In [75]:
tensor_A[:2]

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

#NewAxis and  Expand_Dims

In [77]:
tensor_B = tensor_A[...,tf.newaxis]
tensor_B

<tf.Tensor: shape=(39, 1), dtype=float16, numpy=
array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.],
       [12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.],
       [24.],
       [25.],
       [26.],
       [27.],
       [28.],
       [29.],
       [30.],
       [31.],
       [32.],
       [33.],
       [34.],
       [35.],
       [36.],
       [37.],
       [38.],
       [39.]], dtype=float16)>

In [78]:
tf.expand_dims(tensor_A, axis=1)

<tf.Tensor: shape=(39, 1), dtype=float16, numpy=
array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.],
       [12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.],
       [24.],
       [25.],
       [26.],
       [27.],
       [28.],
       [29.],
       [30.],
       [31.],
       [32.],
       [33.],
       [34.],
       [35.],
       [36.],
       [37.],
       [38.],
       [39.]], dtype=float16)>

#Basic Opeartions

In [79]:
tensor_A

<tf.Tensor: shape=(39,), dtype=float16, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
      dtype=float16)>

In [80]:
tensor_A +10


<tf.Tensor: shape=(39,), dtype=float16, numpy=
array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
       24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36.,
       37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
      dtype=float16)>

In [81]:
tensor_A-10

<tf.Tensor: shape=(39,), dtype=float16, numpy=
array([-9., -8., -7., -6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.,
       17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
      dtype=float16)>

In [82]:
tensor_A*10

<tf.Tensor: shape=(39,), dtype=float16, numpy=
array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.,
       120., 130., 140., 150., 160., 170., 180., 190., 200., 210., 220.,
       230., 240., 250., 260., 270., 280., 290., 300., 310., 320., 330.,
       340., 350., 360., 370., 380., 390.], dtype=float16)>

In [83]:
tensor_A/10

<tf.Tensor: shape=(39,), dtype=float16, numpy=
array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
      dtype=float16)>

In [84]:
tf.math.add(tensor_A,10)

<tf.Tensor: shape=(39,), dtype=float16, numpy=
array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
       24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36.,
       37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
      dtype=float16)>

In [85]:
tf.math.subtract(tensor_A,10)

<tf.Tensor: shape=(39,), dtype=float16, numpy=
array([-9., -8., -7., -6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.,
       17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
      dtype=float16)>

In [86]:
tf.math.multiply(tensor_A,10)

<tf.Tensor: shape=(39,), dtype=float16, numpy=
array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.,
       120., 130., 140., 150., 160., 170., 180., 190., 200., 210., 220.,
       230., 240., 250., 260., 270., 280., 290., 300., 310., 320., 330.,
       340., 350., 360., 370., 380., 390.], dtype=float16)>

In [87]:
tf.math.divide(tensor_A,10)

<tf.Tensor: shape=(39,), dtype=float16, numpy=
array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
      dtype=float16)>

#Matrix Multiplication

In [88]:
matrix_1 = tf.constant([
                        [10,4],[5,3],[5,2]
])
matrix_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  4],
       [ 5,  3],
       [ 5,  2]], dtype=int32)>

In [89]:
matrix_2 = tf.constant([
                        [1,4],[7,4],[6,3]
])
matrix_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [7, 4],
       [6, 3]], dtype=int32)>

In [91]:
tf.matmul(tf.transpose(matrix_1),matrix_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[75, 75],
       [37, 34]], dtype=int32)>

In [92]:
tf.matmul(matrix_1,tf.transpose(matrix_2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[26, 86, 72],
       [17, 47, 39],
       [13, 43, 36]], dtype=int32)>

In [93]:
matrix_1.shape, matrix_2.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

#Change DataType

In [101]:
matrix_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  4],
       [ 5,  3],
       [ 5,  2]], dtype=int32)>

In [102]:
tf.cast(matrix_1, dtype=tf.float32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  4.],
       [ 5.,  3.],
       [ 5.,  2.]], dtype=float32)>

In [103]:
tf.cast(matrix_2, dtype=tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 4.],
       [7., 4.],
       [6., 3.]], dtype=float16)>

#Aggregate

In [104]:
matrix_3= tf.constant([
                       [-3,-5],[-6,-3],[-4,-6]
])
matrix_3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[-3, -5],
       [-6, -3],
       [-4, -6]], dtype=int32)>

In [105]:
tf.abs(matrix_3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 3],
       [4, 6]], dtype=int32)>

In [106]:
print(tf.reduce_min(matrix_1))
print(tf.reduce_mean(matrix_1))
print(tf.reduce_sum(matrix_1))
print(tf.reduce_max(matrix_1))

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(29, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


#VARIANCE and STANDARD DEVIATION

In [107]:
matrix_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  4],
       [ 5,  3],
       [ 5,  2]], dtype=int32)>

In [111]:
tf.math.reduce_variance(tensor_A)

<tf.Tensor: shape=(), dtype=float16, numpy=126.7>

In [112]:
tf.math.reduce_std(tensor_A)

<tf.Tensor: shape=(), dtype=float16, numpy=11.26>

#ARGMAX AND ARGMIN

In [113]:
matrix_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  4],
       [ 5,  3],
       [ 5,  2]], dtype=int32)>

In [114]:
tf.argmax(matrix_1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0])>

In [118]:
tf.argmin(matrix_1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 2])>