#Practices

In [68]:
import tensorflow as tf
import numpy as np

In [69]:
tensor_A = tf.constant(0,3)

In [70]:
tensor_A

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [71]:
scalar =  tf.constant([1,4])
scalar

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [72]:
scalar.ndim

1

In [73]:
scalar.shape

TensorShape([2])

In [74]:
vector = tf.constant([
                      [1,2],[1,1],[3,4],[6,7]
])
vector

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 1],
       [3, 4],
       [6, 7]], dtype=int32)>

In [75]:
vector.ndim

2

In [76]:
vector.shape

TensorShape([4, 2])

In [77]:
vector.dtype

tf.int32

In [78]:
matrix = tf.constant([[1,2],[4,5],[6,7],[8,5]])

matrix

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [6, 7],
       [8, 5]], dtype=int32)>

In [79]:
matrix.ndim

2

In [80]:
matrix.dtype

tf.int32

In [81]:
matrix= tf.Variable([
                     [1,3],[5,7],[8,9],[2,4],[6,3],[6,4]
], dtype=tf.float32)

matrix

<tf.Variable 'Variable:0' shape=(6, 2) dtype=float32, numpy=
array([[1., 3.],
       [5., 7.],
       [8., 9.],
       [2., 4.],
       [6., 3.],
       [6., 4.]], dtype=float32)>

In [82]:
matrix.dtype

tf.float32

In [83]:
matrix.shape

TensorShape([6, 2])

In [84]:
matrix.shape[0]

6

In [85]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(1,3))

In [86]:
random_1

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.7565803 , -0.06854702,  0.07595026]], dtype=float32)>

In [87]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(1,2))

In [88]:
random_2

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.7493447 , 0.73561966]], dtype=float32)>

In [89]:
not_shuffled = tf.constant([
                            [1,3],[4,3],[6,4],[7,3]
])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[7, 3],
       [1, 3],
       [4, 3],
       [6, 4]], dtype=int32)>

In [90]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 4],
       [1, 3],
       [7, 3]], dtype=int32)>

In [91]:
tf.ones(shape=[1,2])

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 1.]], dtype=float32)>

In [92]:
tf.zeros(shape=(1,4))

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>

In [93]:
numpy_A = np.arange(1,25, dtype=np.int16)

In [94]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [95]:
tensor_A = tf.constant(numpy_A)

In [96]:
tensor_A

<tf.Tensor: shape=(24,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)>

In [97]:
print(tensor_A.dtype)
print(tensor_A.shape)
print(tensor_A.ndim)
print(tensor_A.shape[0])
print(tensor_A.shape[-1])
print(tf.size(tensor_A))
print(tf.size(tensor_A).numpy())

<dtype: 'int16'>
(24,)
1
24
24
tf.Tensor(24, shape=(), dtype=int32)
24


In [98]:
tensor_A

<tf.Tensor: shape=(24,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)>

In [99]:
tensor_A[:1]

<tf.Tensor: shape=(1,), dtype=int16, numpy=array([1], dtype=int16)>

In [100]:
tensor_A[:0]

<tf.Tensor: shape=(0,), dtype=int16, numpy=array([], dtype=int16)>

In [101]:
tensor_A+10

<tf.Tensor: shape=(24,), dtype=int16, numpy=
array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34], dtype=int16)>

In [102]:
tensor_A-10

<tf.Tensor: shape=(24,), dtype=int16, numpy=
array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14], dtype=int16)>

In [103]:
matrix_1= tf.constant([
                       [1,3],[5,3],[5,7]
])

In [104]:
matrix_2 = tf.constant([
                        [4,3],[6,4],[5,6]
])

In [105]:
# tf.matmul(matrix_1, matrix_2)

In [106]:
tf.transpose(matrix_1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 5, 5],
       [3, 3, 7]], dtype=int32)>

In [107]:
tf.matmul(tf.transpose(matrix_1), matrix_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[59, 53],
       [65, 63]], dtype=int32)>

In [108]:
matrix_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [5, 3],
       [5, 7]], dtype=int32)>

In [109]:
tf.cast(matrix_1,dtype=tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 3.],
       [5., 3.],
       [5., 7.]], dtype=float16)>

In [110]:
tf.abs(matrix_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [5, 3],
       [5, 7]], dtype=int32)>

In [111]:
E= tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([88, 17, 66, 59,  2, 51, 87,  1, 48, 40,  2, 22, 78, 40, 16, 48, 45,
       84, 61, 40, 58, 84, 29, 17, 19, 15, 58, 15, 61, 67, 74, 96,  3, 79,
       28, 28, 76, 67,  3, 10, 64, 11, 89, 80, 17, 94, 91, 78, 58, 76])>

In [112]:
tf.reduce_min(E)


<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [113]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [114]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [115]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2440>

In [116]:
matrix_1.shape, matrix_2.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [117]:
tf.matmul(tf.transpose(matrix_1), matrix_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[59, 53],
       [65, 63]], dtype=int32)>

In [118]:
tf.transpose(matrix_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 6, 5],
       [3, 4, 6]], dtype=int32)>

In [119]:
# matrix_1 @ matrix_2

In [120]:
tf.transpose(matrix_1) @ matrix_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[59, 53],
       [65, 63]], dtype=int32)>

In [121]:
print(tf.__verison__)

AttributeError: ignored

In [122]:
matrix_3 = matrix_2[...,tf.newaxis]

In [123]:
matrix_3

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[4],
        [3]],

       [[6],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [124]:
tf.expand_dims(matrix_2,axis=1)

<tf.Tensor: shape=(3, 1, 2), dtype=int32, numpy=
array([[[4, 3]],

       [[6, 4]],

       [[5, 6]]], dtype=int32)>