In [2]:
import tensorflow as tf

not_shuffled = tf.constant([
  [1,2], [3,5], [6,7], [8,9],
])

not_shuffled

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 5],
       [6, 7],
       [8, 9]], dtype=int32)>

In [6]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[8, 9],
       [6, 7],
       [3, 5],
       [1, 2]], dtype=int32)>

In [12]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[6, 7],
       [1, 2],
       [3, 5],
       [8, 9]], dtype=int32)>

In [17]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled , seed=42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 2],
       [8, 9]], dtype=int32)>

In [29]:
shuffle1= tf.constant([
                       [1,3],[4,5],[6,8],[1,4]
])

shuffle2= tf.constant([
                       [3,1],[4,6],[2,5],[6,9]
])

shuffle3= tf.constant([
                       [3,6],[1,8],[3,7],[2,9]
])

shuffle4= tf.constant([
                       [3,1],[4,6],[2,5],[6,9]
])

shuffle5= tf.constant([
                       [4,1],[2,7],[1,9],[4,7]
])


tf.random.set_seed(42)

tf.random.shuffle(shuffle1 ,seed=42)
tf.random.shuffle(shuffle2 ,seed=42)
tf.random.shuffle(shuffle3, seed=42)
tf.random.shuffle(shuffle4 ,seed=42)
tf.random.shuffle(shuffle5 ,seed=42)

shuffle1, shuffle2, shuffle3, shuffle4, shuffle5

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 3],
        [4, 5],
        [6, 8],
        [1, 4]], dtype=int32)>, <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[3, 1],
        [4, 6],
        [2, 5],
        [6, 9]], dtype=int32)>, <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[3, 6],
        [1, 8],
        [3, 7],
        [2, 9]], dtype=int32)>, <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[3, 1],
        [4, 6],
        [2, 5],
        [6, 9]], dtype=int32)>, <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[4, 1],
        [2, 7],
        [1, 9],
        [4, 7]], dtype=int32)>)