In [1]:
import tensorflow as tf
import numpy as np

In [2]:
squuexe = tf.constant(tf.random.normal(shape=[50]), shape=(1,1,1,50))
squuexe

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[ 0.27776766, -0.3715602 , -0.6624637 , -0.7849269 ,
           1.4974091 , -1.1607269 ,  0.4859163 ,  0.13662398,
           0.12920295,  0.34626505, -0.43553507,  1.1125343 ,
           0.20557782, -0.80144846,  0.5818976 ,  0.49544322,
           0.8087089 ,  0.70093286, -1.3903309 ,  0.33031744,
          -0.78588533,  0.0733199 ,  0.25745222,  1.9841747 ,
           0.29006952, -0.65295225,  1.4448742 ,  0.63016796,
          -1.2429354 , -0.74281836, -1.0364022 ,  0.40046263,
           0.4261096 ,  0.28432465, -1.545266  , -1.477863  ,
          -0.66920763, -0.08289614,  1.1511824 , -0.31080765,
          -1.0752456 , -0.05535458,  0.60683954, -0.0637965 ,
           1.0122898 , -0.47096506, -0.9709066 ,  1.7545013 ,
          -0.399513  ,  0.55347735]]]], dtype=float32)>

In [5]:
tf.squeeze(squuexe)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([ 0.27776766, -0.3715602 , -0.6624637 , -0.7849269 ,  1.4974091 ,
       -1.1607269 ,  0.4859163 ,  0.13662398,  0.12920295,  0.34626505,
       -0.43553507,  1.1125343 ,  0.20557782, -0.80144846,  0.5818976 ,
        0.49544322,  0.8087089 ,  0.70093286, -1.3903309 ,  0.33031744,
       -0.78588533,  0.0733199 ,  0.25745222,  1.9841747 ,  0.29006952,
       -0.65295225,  1.4448742 ,  0.63016796, -1.2429354 , -0.74281836,
       -1.0364022 ,  0.40046263,  0.4261096 ,  0.28432465, -1.545266  ,
       -1.477863  , -0.66920763, -0.08289614,  1.1511824 , -0.31080765,
       -1.0752456 , -0.05535458,  0.60683954, -0.0637965 ,  1.0122898 ,
       -0.47096506, -0.9709066 ,  1.7545013 , -0.399513  ,  0.55347735],
      dtype=float32)>

In [6]:
val = tf.constant([
                   [2,5],[6,4],[4,3]                   
])
val

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [6, 4],
       [4, 3]], dtype=int32)>

In [7]:
tf.one_hot(val, depth=5)

<tf.Tensor: shape=(3, 2, 5), dtype=float32, numpy=
array([[[0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.]],

       [[0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]]], dtype=float32)>

In [8]:
tf.one_hot(val, depth=4, on_value='Hey! I am On Value', off_value='Hey! I am Off Value')

<tf.Tensor: shape=(3, 2, 4), dtype=string, numpy=
array([[[b'Hey! I am Off Value', b'Hey! I am Off Value',
         b'Hey! I am On Value', b'Hey! I am Off Value'],
        [b'Hey! I am Off Value', b'Hey! I am Off Value',
         b'Hey! I am Off Value', b'Hey! I am Off Value']],

       [[b'Hey! I am Off Value', b'Hey! I am Off Value',
         b'Hey! I am Off Value', b'Hey! I am Off Value'],
        [b'Hey! I am Off Value', b'Hey! I am Off Value',
         b'Hey! I am Off Value', b'Hey! I am Off Value']],

       [[b'Hey! I am Off Value', b'Hey! I am Off Value',
         b'Hey! I am Off Value', b'Hey! I am Off Value'],
        [b'Hey! I am Off Value', b'Hey! I am Off Value',
         b'Hey! I am Off Value', b'Hey! I am On Value']]], dtype=object)>

In [9]:
val

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [6, 4],
       [4, 3]], dtype=int32)>

In [12]:
tf.math.add(val,10)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12, 15],
       [16, 14],
       [14, 13]], dtype=int32)>

In [14]:
tf.range(1,10)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [15]:
tf.square(val)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4, 25],
       [36, 16],
       [16,  9]], dtype=int32)>

In [17]:
tf.sqrt(tf.cast(val, dtype=tf.float32))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.4142135, 2.236068 ],
       [2.4494898, 2.       ],
       [2.       , 1.7320508]], dtype=float32)>

In [19]:
tf.math.log(tf.cast(val, dtype=tf.float32))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6931472, 1.609438 ],
       [1.7917595, 1.3862944],
       [1.3862944, 1.0986123]], dtype=float32)>

In [20]:
numpy_A = tf.constant(np.array([
                                [2,3],[5,3],[6,3]
]))


In [21]:
tensor_A = tf.constant([
                        [2,3],[5,3],[6,3]
])

In [22]:
numpy_A.dtype

tf.int64

In [23]:
tensor_A.dtype

tf.int32

In [24]:
np.array(tensor_A)

array([[2, 3],
       [5, 3],
       [6, 3]], dtype=int32)

In [25]:
tf.constant(numpy_A)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[2, 3],
       [5, 3],
       [6, 3]])>

In [ ]:
numpy_A = tf.constant([
                       [4,5],[5,3],[3,2]

])
numpy_A