In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [4]:
X = tf.constant([2,4,56,6,4,3,45,4])
y = tf.constant([6,5,4,53,5,23,65,8])

X,y

(<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 2,  4, 56,  6,  4,  3, 45,  4], dtype=int32)>,
 <tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 6,  5,  4, 53,  5, 23, 65,  8], dtype=int32)>)

In [19]:
#Set_Random Values

tf.random.set_seed(42)

#Create_Model

model = tf.keras.Sequential([
                             tf.keras.layers.Dense(1)
])

#Compiling a Model

model.compile(
    loss=tf.keras.losses.mae ,
    optimizer = tf.keras.optimizers.SGD() ,
    metrics=['mae']
    
)

#Fit a Model 

model.fit(tf.expand_dims(X, axis=1),y , epochs=5)

Epoch 1/5
1/1 [==============================] - 0s 297ms/step - loss: 19.2699 - mae: 19.2699
Epoch 2/5
1/1 [==============================] - 0s 7ms/step - loss: 19.2418 - mae: 19.2418
Epoch 3/5
1/1 [==============================] - 0s 7ms/step - loss: 19.2137 - mae: 19.2137
Epoch 4/5
1/1 [==============================] - 0s 8ms/step - loss: 19.1855 - mae: 19.1855
Epoch 5/5
1/1 [==============================] - 0s 5ms/step - loss: 19.1574 - mae: 19.1574


# Once More

In [20]:
val1 = tf.constant([5,3,5,7,9,2,6,1,4,0])
val2 = tf.constant([6,7,3,1,2,5,0,7,9,8])

val1, val2


(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([5, 3, 5, 7, 9, 2, 6, 1, 4, 0], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([6, 7, 3, 1, 2, 5, 0, 7, 9, 8], dtype=int32)>)

In [21]:
# Set Random values

tf.random.set_seed(42)

# Create A model

model = tf.keras.Sequential([
                             tf.keras.layers.Dense(1)
])

# Compiling a Model

model.compile(
    loss = tf.keras.losses.mae ,
    optimizer = tf.keras.optimizers.SGD() ,
    metrics = ['mae']
)

# Fit a Model

model.fit(tf.expand_dims(val1, axis=1), val2 , epochs=8)


Epoch 1/8
1/1 [==============================] - 0s 319ms/step - loss: 4.3140 - mae: 4.3140
Epoch 2/8
1/1 [==============================] - 0s 7ms/step - loss: 4.3120 - mae: 4.3120
Epoch 3/8
1/1 [==============================] - 0s 13ms/step - loss: 4.3100 - mae: 4.3100
Epoch 4/8
1/1 [==============================] - 0s 6ms/step - loss: 4.3080 - mae: 4.3080
Epoch 5/8
1/1 [==============================] - 0s 11ms/step - loss: 4.3060 - mae: 4.3060
Epoch 6/8
1/1 [==============================] - 0s 10ms/step - loss: 4.3040 - mae: 4.3040
Epoch 7/8
1/1 [==============================] - 0s 13ms/step - loss: 4.3020 - mae: 4.3020
Epoch 8/8
1/1 [==============================] - 0s 5ms/step - loss: 4.3000 - mae: 4.3000


In [22]:
model.predict([23])

array([[12.775382]], dtype=float32)