# **Import Libraries**

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# **Deep Learning**

**Deep Learning is Subfield of Machine learning**

**In Machine Learning Algorithm, We have Input and Ideal Output to figure out Ideal rules**


# **Why Use Deep Learning**


**For Complex Problem , Can you think of all rules.**

**Deep Learning is Good for:**

*   Problem With Long List of Rules
*   Continusly Changing Environment
*   Discovering Insights With Large Collection


**Deep Learning is Not good for:**

* When You need Explainability 

* When Traditional Method is better

* When Error Are Unacceptable

* When You Don't Have Much Data

* Machine Learning have Sutructured Data

* Deep Learning Have Unsutructured Data

# **Neural Networks**

**Turning data into numbers**

**Represent These numbers in pattern**

**These Pattern provide representation output**

**These Representation Output Converted to final output**


# **Anatomy of Neural Network**

**Input_layer**
**Hidden_layer**
**Output_layer**


# **Types of Transfer Learning**

**Supervised Learning**

**Unsupervised Learning**

**Semi-Supervised Learning**

**Transfer Learning**


# **What is TensorFlow**

**End to End Platform for Machine Learning**

**Write Fast Deep Learning Code in Python**

**Access pre-built modes**

**whole stack, processes,model,deploy,model**

**Originally Designed & Used by Google**


# **Why Tensorflow**

**Easy Building Model**

**Model Robust ML Production**

**Powerful experimentation For Research**


# **GPU/TPU**


**Graphic Processing Unit & Tensor Processing Unit**

# **Tensor**

**Represent Information In Number**
**Represent Some sort of data in number**


# **Tensorflow Workflow**

**Get data Ready**

**Build or pick mode**

**Fit the model to data**

**Evaluate The Model**

**Improve Through Experimentation**

**Save and Reload The Model**


# **Avoid The Thing**

**Overthinking Process**

**The "I Can't learn it" mentally**


# **Lets Code**

**goto colab.research.google.com**

**Create NEW Notebook**



In [3]:
print(tf.__version__)

2.7.0


# **Tf.Constant**

In [5]:
scalar = tf.constant(2,3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [6]:
vector = tf.constant([2,3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [7]:
matrix = tf.constant([
                      [2,3],[4,2]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 2]], dtype=int32)>

In [8]:
tensor = tf.constant([
                      [2,3],[4,2],[4,1]
])

tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 2],
       [4, 1]], dtype=int32)>

In [9]:
scalar.ndim

0

In [10]:
vector.ndim

1

In [11]:
matrix.ndim

2

In [12]:
tensor.ndim

2

In [13]:
another_matrix = tf.constant([
                              [10,3],[10,5],[1,4]
], dtype=tf.float16)

In [14]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  3.],
       [10.,  5.],
       [ 1.,  4.]], dtype=float16)>

In [15]:
another_matrix.ndim

2

In [16]:
another_matrix.shape

TensorShape([3, 2])

In [17]:
another_matrix.dtype

tf.float16

In [21]:
tensor = tf.constant([
                      [
                       [1,3,4], [2,3,4],[1,5,6]
                       ]
                      ,
                      [
                       [2,4,5],[4,1,2],[5,1,0]
                      ],
                      [
                       [2,4,1],[4,1,5],[2,0,1]
                      ]
])

tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 3, 4],
        [2, 3, 4],
        [1, 5, 6]],

       [[2, 4, 5],
        [4, 1, 2],
        [5, 1, 0]],

       [[2, 4, 1],
        [4, 1, 5],
        [2, 0, 1]]], dtype=int32)>

In [22]:
tensor.ndim

3

In [23]:
tensor.shape

TensorShape([3, 3, 3])

 **Scalar Is Single Number**

 **Vector is Number with Direction**

 **Matrix is 2-Dimensional array of Number**

 **(N can Number, 0 Dimensional Tensor)**



# **Tf.variable**

In [24]:
changeable_tensor = tf.Variable([10,7])

In [25]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [26]:
changeable_tensor = tf.Variable(10,4)

In [27]:
changeable_tensor

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

If You Want to change Value in Tf.variable then you use assign() method

In [29]:
changeable_tensor.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=2>

In [30]:
changeable_tensor

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

In [31]:
changeable_tensor = tf.Variable([10,3])

In [32]:
changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

In [33]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

# **Random Tensors**

**Random Tensor are tensors of some Arbitrary size which contain Random Number**

**Initialize With Random Weights**

**Show Example**

**Update Representation Output**

**Repeat With More Examples**



In [34]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(2,3))

random_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

# **Shuffle The Order Of Element**



In [35]:
not_shuffled = tf.constant([
                            [10,7],[1,4],[4,1],[8,4]
])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 4,  1],
       [ 1,  4],
       [ 8,  4],
       [10,  7]], dtype=int32)>

**Everytime We Run it, It Provide Us Different Order of pair Until We set Seed(42)**



In [36]:
tf.random.set_seed(42)

tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 4,  1],
       [10,  7],
       [ 8,  4]], dtype=int32)>

# **Creating Tensor With Numpy Array**

**If We want our Shuffle To be some order then We Used Global Seed As Well as operation seed**




In [37]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [38]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [39]:
# You Can Also Turn Numpy array into Tensor

# Difference B/W Numpy Array & Tensor Array is That  Tensor Can Be Run On GPU

In [40]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [41]:
# Tuning

A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [42]:
X = tf.constant(A)

In [43]:
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# **Gathering Information From Tensor**

**Sometime You Cell Doesn't Work it is Better For You To Run Before**

**Shape , Rank, Axis/Rotation, Size**



In [44]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [45]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [46]:
rank_4_tensor.ndim

4

In [47]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [48]:
rank_4_tensor.ndim

4

In [49]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

# **Get Various Attributes Of Our Tensor**

In [50]:
print(rank_4_tensor.dtype)
print(rank_4_tensor.ndim)
print(rank_4_tensor.shape)
print(rank_4_tensor.shape[0])
print(tf.size(rank_4_tensor))
print(tf.size(rank_4_tensor).numpy())

<dtype: 'float32'>
4
(2, 3, 4, 5)
2
tf.Tensor(120, shape=(), dtype=int32)
120


# **Indexing Tensors**

In [51]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [52]:
rank_4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

# **Add Extra Dimenstion To Our Rank 2 Tensor**

In [53]:
rank_3_tensor = rank_4_tensor[..., tf.newaxis]

In [54]:
rank_3_tensor

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
     

In [55]:
# Alternate Of TF New Axis
tf.expand_dims(rank_4_tensor, axis=-1)


<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
     

# **Manipulating Tensor**

In [56]:
tensor = tf.constant([
                      [10,3],[5,3]
])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [ 5,  3]], dtype=int32)>

In [57]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 13],
       [15, 13]], dtype=int32)>

In [58]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -7],
       [-5, -7]], dtype=int32)>

In [59]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  30],
       [ 50,  30]], dtype=int32)>

In [60]:
tensor/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.3],
       [0.5, 0.3]])>

# **Matrix Manipulation**

In [61]:
# In Machine Learning , Matrix Multiplication Is one Of The Moset Common Operation

In [62]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[115,  39],
       [ 65,  24]], dtype=int32)>

**There are Our two Rules Our Tensor(Matrices)  Need To fulfill If we are Going To Matrix Multiplication**

**i- Inner Dimension Must Watch(imp)**
**ii- Resulting Matrix Has Shape of Outer Dimension**

**To change The Shape of any matrix**

In [65]:
# We Have Done Because Inner Dimension Must Watch

In [66]:
tf.transpose(X)

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]], dtype=int32)>

# **The Dot Product**

In [72]:
# You can Perform Matrix Multiplication Using:

# TF.matmul()
# TF.tensordot()

# You Should Use Transpose (Rather Than Shape) When You Try Matrix Multiplications & one Axes are not Line Up

# **Changing DataType of Tensor**

In [74]:
D = tf.cast(X, dtype=tf.float16)

In [75]:
D

<tf.Tensor: shape=(2, 3, 4), dtype=float16, numpy=
array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]], dtype=float16)>

In [76]:
tf.abs(D)

<tf.Tensor: shape=(2, 3, 4), dtype=float16, numpy=
array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]], dtype=float16)>

 **Get The Minimum**
 **Get The Maximum**
 **Get The Mean Of Tensor**
 **Get The Sum of Tensor**

In [77]:
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=float16, numpy=1.0>

In [78]:
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=float16, numpy=24.0>

In [79]:
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=float16, numpy=12.5>

In [80]:
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=float16, numpy=300.0>

# **Variance & STD**

In [81]:
tf.math.reduce_std(tf.cast(D, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=6.92>

In [82]:
tf.math.reduce_variance(tf.cast(D, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=47.9>

In [83]:
tf.argmax(D)

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [84]:
tf.argmin(D)

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

# **Squeezing A tensor**

In [86]:
tf.random.set_seed(42)

G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))

In [87]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [88]:
G_squeezed = tf.squeeze(G)

In [89]:
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# **One Hot Encoding**

In [92]:
lise = tf.constant([
                    [2,4],[2,4],[5,1]
])



In [93]:
tf.one_hot(lise, depth=4)

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[0., 0., 1., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 1., 0., 0.]]], dtype=float32)>

In [94]:
tf.one_hot(lise, depth=3, on_value='I am On Value', off_value = 'I am Off Value')

<tf.Tensor: shape=(3, 2, 3), dtype=string, numpy=
array([[[b'I am Off Value', b'I am Off Value', b'I am On Value'],
        [b'I am Off Value', b'I am Off Value', b'I am Off Value']],

       [[b'I am Off Value', b'I am Off Value', b'I am On Value'],
        [b'I am Off Value', b'I am Off Value', b'I am Off Value']],

       [[b'I am Off Value', b'I am Off Value', b'I am Off Value'],
        [b'I am Off Value', b'I am On Value', b'I am Off Value']]],
      dtype=object)>

# **More Math Operations**

.range()

.sqrt()

.Square()

.Log()




# **Using Tensorflow With Numpy**

In [98]:
J = tf.constant(np.array([
                          [10,4],[5,2]
]))

In [99]:
J

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[10,  4],
       [ 5,  2]])>

In [100]:
H = np.array([
              [10,4],[5,2]
])

In [101]:
H

array([[10,  4],
       [ 5,  2]])

In [102]:
J==H

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [103]:
I = tf.constant(J)

In [104]:
M = np.array(H)

In [105]:
I==M

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [107]:
I.dtype, M.dtype, J.dtype, H.dtype

(tf.int64, dtype('int64'), tf.int64, dtype('int64'))

In [108]:
# Default Type Of Each Are Slightly Different

# **This Is End OF Tensor FLOW ALL BASIC FUNCTIONALITIES**