# **Tensor Flow Practice**

In [1]:
import tensorflow as tf
import numpy as np

**Constant**

In [2]:
scalar =  tf.constant(2,3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [3]:
scalar.ndim

0

In [5]:
vector = tf.constant([2,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([
                      [2,5],[5,6]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 5],
       [5, 6]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
tensors = tf.constant([
                       [4,6],[6,4],[6,3],[3,6]
])
tensors

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 6],
       [6, 4],
       [6, 3],
       [3, 6]], dtype=int32)>

In [10]:
tensors.ndim

2

**Variable**

In [11]:
variable = tf.Variable([2,5])
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 5], dtype=int32)>

In [12]:
variable[0].assign(4)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [13]:
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [14]:
variable2 = tf.Variable(25,4)

In [15]:
variable2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>

In [16]:
variable2.assign(4)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=4>

In [17]:
variable2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>

**Random  Values**

In [18]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(5,7))
random_1

<tf.Tensor: shape=(5, 7), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763,
        -1.8107855 ,  0.09988727],
       [-0.50998646, -0.7535805 , -0.57166284,  0.1480774 , -0.23362993,
        -0.3522796 ,  0.40621263],
       [-1.0523509 ,  1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,
         0.99009085, -0.0876323 ],
       [-0.635568  , -0.6161736 , -1.9441465 , -0.48293006, -0.52447474,
        -1.0345329 ,  1.3066901 ],
       [-1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ,  0.45331386,
         1.1487608 , -1.2659091 ]], dtype=float32)>

In [19]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(5,7))
random_2

<tf.Tensor: shape=(5, 7), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ,
        0.52027524, 0.8736881 ],
       [0.46921718, 0.63932586, 0.6467117 , 0.96246755, 0.41009164,
        0.86540747, 0.8862978 ],
       [0.27795732, 0.8857763 , 0.2179842 , 0.29115117, 0.03953862,
        0.8136791 , 0.8139852 ],
       [0.52180684, 0.12496924, 0.5488483 , 0.7755773 , 0.6184403 ,
        0.24936223, 0.89341843],
       [0.28422844, 0.70332646, 0.2622137 , 0.4432162 , 0.466465  ,
        0.05981874, 0.40098202]], dtype=float32)>

In [20]:
random_1==random_2

<tf.Tensor: shape=(5, 7), dtype=bool, numpy=
array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])>

**Shuffle**

In [21]:
not_shuffle = tf.constant([
                           [4,6],[7,4],[2,5],[6,8]
])
not_shuffle

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 6],
       [7, 4],
       [2, 5],
       [6, 8]], dtype=int32)>

In [24]:
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[6, 8],
       [7, 4],
       [2, 5],
       [4, 6]], dtype=int32)>

In [27]:
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[7, 4],
       [2, 5],
       [4, 6],
       [6, 8]], dtype=int32)>

In [30]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[7, 4],
       [2, 5],
       [4, 6],
       [6, 8]], dtype=int32)>

**Numpy**

In [31]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
numpy_A = np.arange(1,34, dtype=np.int64)

In [34]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [35]:
tensor_A = tf.constant(numpy_A)

In [36]:
tensor_A

<tf.Tensor: shape=(33,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])>

In [37]:
tensor_A == numpy_A

<tf.Tensor: shape=(33,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])>

In [41]:
numpy_B = np.random.random_sample(30)

In [42]:
numpy_B

array([0.52170169, 0.81237469, 0.30478183, 0.61837547, 0.89885193,
       0.68436301, 0.20885821, 0.47539827, 0.79206581, 0.46149559,
       0.94731727, 0.96656068, 0.00604941, 0.58484313, 0.92541109,
       0.54506948, 0.16497413, 0.95144718, 0.77302981, 0.50783979,
       0.04715503, 0.78197399, 0.46364045, 0.82110156, 0.0909457 ,
       0.63181348, 0.24155285, 0.21597394, 0.68673379, 0.30826864])

**Getting Information**

In [43]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [44]:
print(numpy_A.ndim)
print(numpy_A.dtype)
print(numpy_A.nbytes)
print(numpy_A.size)
print(numpy_A.itemsize)
print(numpy_A.shape)
print(numpy_A.shape[0])
print(numpy_A.shape[-1])
print(tf.size(numpy_A))
print(tf.size(numpy_A).numpy())


1
int64
264
33
8
(33,)
33
33
tf.Tensor(33, shape=(), dtype=int32)
33


**Indexing**

In [45]:
tensor_A

<tf.Tensor: shape=(33,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])>

In [46]:
tensor_A[1:]

<tf.Tensor: shape=(32,), dtype=int64, numpy=
array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])>

In [47]:
tensor_A[6:]

<tf.Tensor: shape=(27,), dtype=int64, numpy=
array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33])>

In [48]:
tensor_A[1:25:2]

<tf.Tensor: shape=(12,), dtype=int64, numpy=array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])>

In [49]:
tensor_A[2::3]

<tf.Tensor: shape=(11,), dtype=int64, numpy=array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])>

In [50]:
numpy_B

array([0.52170169, 0.81237469, 0.30478183, 0.61837547, 0.89885193,
       0.68436301, 0.20885821, 0.47539827, 0.79206581, 0.46149559,
       0.94731727, 0.96656068, 0.00604941, 0.58484313, 0.92541109,
       0.54506948, 0.16497413, 0.95144718, 0.77302981, 0.50783979,
       0.04715503, 0.78197399, 0.46364045, 0.82110156, 0.0909457 ,
       0.63181348, 0.24155285, 0.21597394, 0.68673379, 0.30826864])

In [51]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [53]:
tensor_B = tensor_A[..., tf.newaxis]

In [54]:
tensor_B

<tf.Tensor: shape=(33, 1), dtype=int64, numpy=
array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33]])>

In [55]:
tensor_C = tf.expand_dims(tensor_A, axis=1)

In [56]:
tensor_C

<tf.Tensor: shape=(33, 1), dtype=int64, numpy=
array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33]])>

In [57]:
tensor_A

<tf.Tensor: shape=(33,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])>

**Basic Opeartion**

In [65]:
print(tensor_A +10)
print(tensor_A-10)
print(tensor_A*10)
print(tensor_A/10)
print(tensor_A**10)
print(tf.math.add(tensor_A, 10))
print(tf.math.subtract(tensor_A,10))
print(tf.math.multiply(tensor_A,10))
print(tf.math.divide(tensor_A,10))





tf.Tensor(
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43], shape=(33,), dtype=int64)
tf.Tensor(
[-9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14
 15 16 17 18 19 20 21 22 23], shape=(33,), dtype=int64)
tf.Tensor(
[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330], shape=(33,), dtype=int64)
tf.Tensor(
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8
 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3], shape=(33,), dtype=float64)
tf.Tensor(
[               1             1024            59049          1048576
          9765625         60466176        282475249       1073741824
       3486784401      10000000000      25937424601      61917364224
     137858491849     289254654976     576650390625    1099511627776
    2015993900449    3570467226624    6131066257801   10240000000000
   1667988097820

**Matrix Multiplications**

In [66]:
matrix_1 = tf.constant([
                        [4,4],[6,3],[2,3]
])
matrix_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 4],
       [6, 3],
       [2, 3]], dtype=int32)>

In [67]:
matrix_2 = tf.constant([
                        [4,6],[8,5],[3,2]
])
matrix_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 6],
       [8, 5],
       [3, 2]], dtype=int32)>

In [68]:
tf.matmul(matrix_1,matrix_2)

InvalidArgumentError: ignored

In [69]:
tf.matmul(tf.transpose(matrix_1), matrix_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[70, 58],
       [49, 45]], dtype=int32)>

In [70]:
tf.matmul(matrix_1, tf.transpose(matrix_2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[40, 52, 20],
       [42, 63, 24],
       [26, 31, 12]], dtype=int32)>

In [71]:
matrix_1.shape

TensorShape([3, 2])

In [79]:
tf.transpose(matrix_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 8, 3],
       [6, 5, 2]], dtype=int32)>

**Aggregate**

In [80]:
tf.abs(matrix_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 6],
       [8, 5],
       [3, 2]], dtype=int32)>

In [83]:
print(tf.math.reduce_min(matrix_1))
print(tf.math.reduce_mean(matrix_1))
print(tf.math.reduce_max(matrix_1))
print(tf.math.reduce_sum(matrix_1))

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)


**Varianve and Std**

In [92]:
tf.math.reduce_variance(tf.cast(matrix_1, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1.5555557>

In [93]:
tf.math.reduce_std(tf.cast(matrix_1, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=1.247>

**Argmax and Argmin**

In [94]:
tf.argmax(matrix_1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>

In [95]:
tf.argmin(matrix_1)


<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 1])>

In [97]:
tf.argsort(matrix_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 0],
       [0, 1]], dtype=int32)>

In [99]:
tf.transpose(matrix_1) @ matrix_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[70, 58],
       [49, 45]], dtype=int32)>

In [104]:
tf.tensordot(tf.transpose(matrix_1),matrix_2 ,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[70, 58],
       [49, 45]], dtype=int32)>