In [2]:
import tensorflow as tf

random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(1,3))
random1

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.7565803 , -0.06854702,  0.07595026]], dtype=float32)>

In [5]:
random1 = tf.random.Generator.from_seed(23)
random2 = tf.random.Generator.from_seed(23)
random1 = random1.normal(shape=(1,3))
random2 = random2.normal(shape=(1,3))

random1, random2 , random1==random2

(<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.1175475 ,  0.03493892, -1.5700307 ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.1175475 ,  0.03493892, -1.5700307 ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 3), dtype=bool, numpy=array([[ True,  True,  True]])>)

In [14]:
random1 = tf.random.Generator.from_seed(42)
random2 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(1,2))
random2 = random2.uniform(shape=(1,2))

random1, random2 , random1==random2

(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.7565803 , -0.06854702]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.7493447 , 0.73561966]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=bool, numpy=array([[False, False]])>)