In [1]:
import tensorflow as tf
import numpy as np
import tensorflow_probability as tfp

In [2]:
matrix_1 = tf.constant([
                        [1,4],[6,4],[6,2]
])
matrix_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [6, 4],
       [6, 2]], dtype=int32)>

In [3]:
tf.math.reduce_variance(tf.cast(matrix_1, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=3.472222>

In [5]:
tf.math.reduce_std(tf.cast(matrix_1, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1.86339>

In [6]:
tf.argmax(matrix_1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>

In [7]:
tf.argmin(matrix_1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 2])>

In [9]:
tf.random.set_seed(42)
E = tf.random.normal(shape=[50])
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 , -2.3880599 ,
       -1.0392479 , -0.5573232 ,  0.539707  ,  1.6994323 ,  0.28893656,
       -1.5066116 , -0.26454744, -0.59722406, -1.9171132 , -0.62044144,
        0.8504023 , -0.40604794, -3.0258412 ,  0.9058464 ,  0.29855987,
       -0.22561555, -0.7616443 , -1.891714  , -0.9384712 ,  0.77852213,
       -0.47338897,  0.97772694,  0.24694404,  0.20573747, -0.5256233 ,
        0.32410017,  0.02545409, -0.10638497, -0.6369475 ,  1.1603122 ,
        0.2507359 , -0.41728497,  0.40125778, -1.4145442 , -0.59318566,
       -1.6617213 ,  0.33567193,  0.10815629,  0.2347968 , -0.56668764,
       -0.35819843,  0.88698626,  0.5274477 ,  0.70402247, -0.33421248],
      dtype=float32)>

In [10]:
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 , -2.3880599 ,
       -1.0392479 , -0.5573232 ,  0.539707  ,  1.6994323 ,  0.28893656,
       -1.5066116 , -0.26454744, -0.59722406, -1.9171132 , -0.62044144,
        0.8504023 , -0.40604794, -3.0258412 ,  0.9058464 ,  0.29855987,
       -0.22561555, -0.7616443 , -1.891714  , -0.9384712 ,  0.77852213,
       -0.47338897,  0.97772694,  0.24694404,  0.20573747, -0.5256233 ,
        0.32410017,  0.02545409, -0.10638497, -0.6369475 ,  1.1603122 ,
        0.2507359 , -0.41728497,  0.40125778, -1.4145442 , -0.59318566,
       -1.6617213 ,  0.33567193,  0.10815629,  0.2347968 , -0.56668764,
       -0.35819843,  0.88698626,  0.5274477 ,  0.70402247, -0.33421248],
      dtype=float32)>

In [11]:
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [12]:
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [13]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.8896698>

In [15]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.94322306>

In [16]:
E
E[tf.argmax(E)]

<tf.Tensor: shape=(), dtype=float32, numpy=1.6994323>

In [17]:
E
E[tf.argmin(E)]

<tf.Tensor: shape=(), dtype=float32, numpy=-3.0258412>

In [18]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=float32, numpy=-3.0258412>

In [19]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=float32, numpy=1.6994323>