#**Variance and Standard Deviation**

In [6]:
import tensorflow as tf
import numpy as np
import tensorflow_probability as tfp

In [2]:
matrix_1 = tf.constant([
                        [1,3],[5,3],[8,7]
])


In [3]:
matrix_2 = tf.constant([
                        [1,4],[6,3],[7,4]
])


In [4]:
matrix_1, matrix_2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 3],
        [5, 3],
        [8, 7]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [6, 3],
        [7, 4]], dtype=int32)>)

In [13]:
tfp.stats.variance(matrix_1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 3], dtype=int32)>

In [14]:
tfp.stats.variance(matrix_2)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 0], dtype=int32)>

In [16]:
# tf.math.reduce_std(matrix_1)

In [18]:
tf.math.reduce_std(tf.cast(matrix_1, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.4324198>

In [19]:
tf.math.reduce_std(tf.cast(matrix_2, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=1.951>